### ISSUE TITLE
Import .wav or .txt files?

### ISSUE THREAD

**Issue by el-ef** [jaakkopasanen/AutoEq#104]
Dear Jaakko,

is there any opportunity to process .wav or .txt files generated with Impulcifer or Room EQ Wizard? I would like to match a few headphones I measured with my in ear microphones.

I would welcome your response!

Best wishes,
Lucas

**Comment by jaakkopasanen** [comment]
Hi. Actually I updated AutoEQ to be able to handle all sorts of file types and formats a while ago because I needed that to read microphone calibration files in Impulcifer. The one thing that is missing is that AutoEQ would read other than CSV files when used from command line.

You should be able to work your way around this simply by renaming your `.txt` file as `.csv` file ie. `HD 800.txt` becomes `HD 800.csv`. It's a hack but should work nevertheless because the way the file reading is implemented. You need to have the file in a directory and you'll just point AutoEQ to access that directory as the input.

**Comment by el-ef** [comment]
> 
> 
> Hi. Actually I updated AutoEQ to be able to handle all sorts of file types and formats a while ago because I needed that to read microphone calibration files in Impulcifer. The one thing that is missing is that AutoEQ would read other than CSV files when used from command line.
> 
> You should be able to work your way around this simply by renaming your `.txt` file as `.csv` file ie. `HD 800.txt` becomes `HD 800.csv`. It's a hack but should work nevertheless because the way the file reading is implemented. You need to have the file in a directory and you'll just point AutoEQ to access that directory as the input.

Thank you very much for the quick response.

I had some doubts that the formatting of the .txt files generated with REW match the requirements of your project since there are actually three columns with the third one listing phase data.
However, renaming and importing them as .csv files appears to work flawlessly! :)

Thanks a lot!

Best wishes and happy holidays,
Lucas
