### ISSUE TITLE
Is it possible to generate graphic EQ from customized parametric EQ settings with AutoEq?

### ISSUE THREAD

**Issue by lisp1** [jaakkopasanen/AutoEq#107]
Hi Jaakko,

I am trying to produce a good fixed band EQ setting for isine20, which is an earphone neither in-ear nor over-ear (strictly speaking). Therefore, I tune a parametric EQ setting myself that sounds best for me, which is different from all isine20 settings in the result repository. I wonder whether it is possible to use AutoEq to generate a graphic EQ setting from my personal parametric EQ setting. I have set up the environment and can now run the program without problem, but among the parameters, I did not find one that allows me to input parametric EQ setting. Is it possible to add such a function that accepts input of customized parametric EQ setting and produces a similar fixed band EQ setting? Thank you and merry Christmas!

**Comment by jaakkopasanen** [comment]
Hi.

In principle it would be possible to add this functionality but since this is a very niche use case I'm going to be honest and say I'll most likely never add this.

I would suggest you to adjust graphic eq settings by ear just like you adjusted the parametric eq settings. In any case that's the only way for best results since 10-band graphic EQs don't fix all the problems and they would benefit from some manual adjustments anyways in most cases.
