### ISSUE TITLE
KZ ZS10 Pro Profile has issues for me.

### ISSUE THREAD

**Issue by TNShark** [jaakkopasanen/AutoEq#110]
I am currently using a mid 2012 Macbook Pro running windows 10 Bootcamp, but whenever I copy and pasted the "KZ ZS10 Pro GraphicEQ.txt" line into the edit text function where I can paste directly into the Equalizer, my KZs are incredibly loud. (Well, any headphone on my computer has been incredibly loud. I had to use headphones at a volume of 5-7 before finding out about Equalizer APO and its loudness correction/preamp functions. Is this because I have bootcamped windows? I am pretty new at this, so I have no idea.) Anyway, I have to use a preamp of -40 dB so that it doesn't blow out my eardrums... Any suggestions? I would love to use these headphones properly tuned, but I'm kind-of lost. (Sorry if I posted this in the wrong place as well, Git-Hub is new for me as well.)

**Comment by jaakkopasanen** [comment]
Hello. I'm afraid I don't know what's going on because I don't use Mac, let alone with Windows installed. It could be that your Mac's headphone amp has a lot of gain which is somehow controlled by the native OS. Running Windows might disable this and you're getting the full power of the amp. I don't really have anything else to suggest but to use the preamp in EqualizerAPO to bring the volume down.
