### ISSUE TITLE
Quick question about Grado GS1000e results

### ISSUE THREAD

**Issue by ratcheer** [jaakkopasanen/AutoEq#121]
One of the entries is out of order. It is also very close in Fc to another entry, so I'm wondering if it is a mistake.

There is an entry for 2020 Hz, then one for 6231, then another for 2384. Is 2384 a mistake? Or are all the entries correct and just out of order?

BTW, my headphones sound awesome with your parameters applied. Thanks for all the great work!

**Comment by jaakkopasanen** [comment]
Hi. It's not a mistake. The Q values (width of the filter) are very different so they both serve a purpose for the end result. Also the first five filters can be used without the last five and that's why the filters are not in order of frequency.

The parametric eq filter optimization is an automatic process that can produce unintuitive results but they are always good.

**Comment by ratcheer** [comment]
Thank you.
