### ISSUE TITLE
Discrepancy between Oratory1990's measurements and repository's EQs?

### ISSUE THREAD

**Issue by IcicleTF** [jaakkopasanen/AutoEq#139]
I wouldn't have any doubt that I'm just misinterpreting the measurements, but I wanted to make sure there weren't any errors.

For this example, the EQs for the HiFiman HE400i in the repository (https://github.com/jaakkopasanen/AutoEq/blob/master/results/oratory1990/harman_over-ear_2018/Hifiman%20HE400i/README.md) has a variety of different filter settings, as well as a different preamp gain than the preliminary PDF published by Oratory1990 (https://www.dropbox.com/s/6oz7qw2gbc6yag3/Hifiman%20HE400i%20%28preliminary%29.pdf?dl=0)

I'm wondering if this discrepancy is an error, or if it has to do with how the original EQs are being interpreted (or transformed, if they're erroneous).

**Comment by jaakkopasanen** [comment]
AutoEQ optimizes the parametric eq filters from scratch instead of using the filter parameters provided by oratory1990. I only read the measurement data from the PDF and all the rest is handled by AutoEQ automatically.

The parametric eq optimization is a stochastic process and the optimizer produces filters which minimize the resulting error. Sometimes the optimizer does decisions which may seem very unintuitive for humans but that's actually a benefit of the optimizer because it can come up with combinations that humans wouldn't think of.

However there is still one thing lacking in AutoEQ's filter optimizer which is the fact that it doesn't avoid high Q positive gain filters which would cause ringing. I intend to implement this in the future.

Another difference between AutoEQ results and oratory1990's own is the bass shelf level which is about 6 dB in original Harman target (used by oratory1990) and 4 dB in AutoEQ. I decided to use lower bass shelf because some headphones would struggle with high bass gains producing a lot of distortion at higher volumes. Also some users might not have enough gain available to achieve sufficient levels with high negative preamp gain required by higher bass boost. In this particular case AutoEQ results actually require higher negative preamp than oratory1990's results.

These are some of the things that come with fully automatic process. There are things I can and will do to improve these but for the time being I would guess that oratory1990's parametric eq filters are a safer bet. Of course AutoEQ support for other equalizer types which oratory1990 doesn't support like convolution and the standard 10 band eq.

**Comment by jaakkopasanen** [comment]
I assume my message answered your question and am closing this issue. You can still add comments or reopen the issue if you have reason to think there are some problems with AutoEq generated parametric eq filters.
