### ISSUE TITLE
KZ AS-10 - New ParametricEQ Setting Creating Squeaking Sound

### ISSUE THREAD

**Issue by RoboJin** [jaakkopasanen/AutoEq#14]
The old one are just fine but as soon as i manually key in the setting or import it to peace, it started to squeaking

**Comment by jaakkopasanen** [comment]
This is most probably due to the filter with center frequency of 24 kHz. The sampling rate for filter optimization was set to 48 kHz and all filters with center frequencies above half of the sampling frequency are folded back into the first half of the spectrum. This does not however protect from filters between 20 kHz and half of the sampling frequency.

I'm using 44.1 kHz as the sampling frequency in the future and will re-process all the results which have filters above 220500 Hz.

Can you test if the problem persist when you change the center frequency to 220500 Hz for that one filter? What device, operating system and software are you using?

**Comment by RoboJin** [comment]
Window 10, EqualiserAPO/Peace GUI.
Yep i change 24000 Hz to 220500 Hz and it work now on PC

But of course it doesn't work on my phone via Viper4Android anymore because of the 24000 Hz n 220500hz.

For now i will just wait for your reprocess

**Comment by jaakkopasanen** [comment]
That frequency was a typo, sorry. I meant of course 22050 Hz, not 220500 Hz. Very interesting though that 220500 Hz worked for you. Could you try again with 22050 Hz? What sampling frequency have you selected on your sound card?

How do you use these settings with Viper4Android? I though there is no way to get Viper4Android working.

**Comment by jaakkopasanen** [comment]
I re-processed all results which have filters with center frequency above 22050 Hz. Could you confirm and close this issue if the problem has been solved?

**Comment by RoboJin** [comment]
Tested your new reprocess result and it's working for 44.1 kHz format. Thanks so much
