### ISSUE TITLE
[Question] 2017 Innerfidelity Compensation Curve vs. SBAF Serious

### ISSUE THREAD

**Issue by xykrr** [jaakkopasanen/AutoEq#149]
Hi, I'm having trouble getting the full picture on something. Is the SBAF Serious target outdated compared to the 2017 Innerfidelity Compensation target? When tuning my headphones with an Innerfidelity measurement, the 2017 target with --bass_boost 4 (obviously, bass boost level purely personal preference) sounds better overall to me. Is this just a coincidence? If not, then why are all the Innerfidelity result uploads using SBAF?

**Comment by jaakkopasanen** [comment]
2017 Innerfidelity compensation curve was developed by Tyll based on his HATS measurements in Harman's reference listening room. These however were never finally approved by Tyll before his retirement so I can't really recommend them.

The SBAF Serious target was created by Superbest Audio Friends forum user called "Serious" who came up with a target curve for the red and blue lines in the Innerfidelity measurement PDFs by listening to various headphones. The red and blue lines are have been compensated with the original "independent of direction" curve which does not represent neutral in any way. I turned the curve by Serious into a raw measurement compensation curve.

I did some listening tests with couple of headphones comparing the 2017 curve and SBAF Serious curve. To my ears the SBAF Serious curve always sounded a lot better. 2017 is quite bright sounding one. That being said, it's completely possible that the 2017 curve sounds better to you since everyone's hearing is unique so it might better match you.

You can see a comparison of 2017, SBAF Serious and a new curve calibrated agains oratory1990's measurements here: https://imgur.com/a/poKKqPt

These are normalized at 1 kHz. What you see is that 2017 curve has a significantly lower bass region. If you were to raise the whole curve up so that the bass region is at the same level as the other curves, you would bump the 3 kHz peak several dBs above the calibrated one while SBAF Serious is a few dBs lower. The 2017 curve is also several dBs hotter in the 4 to 7 kHz region even without raising the entire curve to get the bass levels match. This explains why the 2017 curve sounds so bright.

Here's the new curve as CSV in case you'd like to try that out too: https://raw.githubusercontent.com/jaakkopasanen/AutoEq/unified-naming/research/calibration/innerfidelity-onear.csv

**Comment by xykrr** [comment]
Ah, I see. Thanks.
Looking into this further, while orratory1990 says that Innerfidelity measurements are incompatible with the Harman target he uses because of different measurements coming from different measurement rigs, it seems they're not _that_ incompatible. I was purposefully avoiding using the 2018 Harman target compensation csv because orratory said that. But, now that I've compared to other targets purpose built for the Innerfidelity measurements, it seems that the 2018 target just isn't that far off. So, I tried that and it seems to make the most satisfying difference.
Am I misguided in saying this? While not technically faithful when used with Innerfidelity measurements, is the Harman over ear 2018 csv "good enough"?

**Comment by xykrr** [comment]
Ah I see, thanks.
The link to the csv file for the new curve is giving me a 404 error. Was it moved?

**Comment by xykrr** [comment]
So, I used the new curve csv. It definitely sounds the best of the bunch. I think the the flatness of both the 2017 Innerfidelity target and this new, calibrated curve from 1200 to 3500 hz compared to SBAF serious is what makes me like them more. It sounds less shrill, that way. But, for the reasons you mentioned, the 2017 target was still too bright. That's alleviated with this new target, among other things.
However, is there a way to --bass_boost without changing the bass response of the new curve? When I bass boosted my equalization, it just has a raised flat line from 20hz to mid-bass. Obviously, this works for most targets But, not this calibrated one.

**Comment by jaakkopasanen** [comment]
The SBAF Serious curve seems to have the scoop around 1200 to 3500 Hz on purpose: https://www.superbestaudiofriends.org/index.php?threads/innerfidelity-fr-target.5560/. Harman target is quite close to the calibrated curve until about 2800 Hz but has a lot more energy in the 4 to 8 kHz range so I wouldn't recommend that blindly either.

The calibrated curve does look quite nice although it does have a bit more energy than SBAF Serious in the 3 kHz range. It's very hard to make these decisions because I can't really conduct listening tests since I have only two pairs of headphones. Unit variance and uniqueness of each listener's hearing would make the conclusions pretty much invalid.
