### ISSUE TITLE
limit frequency range

### ISSUE THREAD

**Issue by DeLub** [jaakkopasanen/AutoEq#150]
Hi,

I'm experimenting with autoeq to equalize my HD600 to a bruel & kjaer target instead of harman kardon, as I like it a bit "flatter" using the sound signature option. Not sure if I 'digitised' the b&k curve correctly, but what I did was:
```
python3 frequency_response.py --input_dir="measurements/oratory1990/data/onear/Sennheiser HD 600" --output_dir="output/hd600-bk" --compensation="compensation/loudspeaker_in-room_flat_2013.csv" --sound_signature="output/bk.csv" --equalize --parametric_eq
```

The results:
| Type    | Fc       |    Q | Gain     |
|:--------|:---------|:-----|:---------|
| Peaking | 19 Hz    | 1.12 | 4.3 dB   |
| Peaking | 92 Hz    | 1.37 | -0.8 dB  |
| Peaking | 159 Hz   | 0.47 | -1.4 dB  |
| Peaking | 383 Hz   | 1.23 | 0.9 dB   |
| Peaking | 1245 Hz  | 0.74 | 2.1 dB   |
| Peaking | 1279 Hz  | 1.87 | -2.5 dB  |
| Peaking | 4346 Hz  | 4.29 | 1.8 dB   |
| Peaking | 5962 Hz  | 4.08 | -2.7 dB  |
| Peaking | 6814 Hz  | 1.86 | 2.9 dB   |
| Peaking | 9735 Hz  | 2.41 | 4.2 dB   |
| Peaking | 11102 Hz | 4.23 | 3.9 dB   |
| Peaking | 17606 Hz | 0.29 | -11.0 dB |
| Peaking | 22050 Hz | 1.53 | -8.4 dB  |

I cannot copy this one to one to my equaliser (I'm using Roon), as the minimum frequency I'm allowed to enter is 20Hz, and the maximum is 22000Hz. I expect that in this particular case this does not lead to any issues, but I do think it might be a good option to indicate minimum and maximum frequencies for the filters.

I'll now try the results (in which I have put the first filter to 20 and the last filter to 22000 Hz) and see how it sounds :)

Thanks for your work!

Regards,
Alex

**Comment by DeLub** [comment]
Stupid me, another option is of course to use the convolution files as Roon also supports those. Might even be a better option?

**Comment by jaakkopasanen** [comment]
Convolution filters are an option indeed. I'm not sure is it better than parametric EQ. In theory they follow the eq curve more closely but that's probably not a big issue in practice. Parametric filters might cause ringing because I don't have an algorithm implemented yet which prevents that (see the high Q filters with positive gain). The same thing probably happens with convolution if there is a sharp peak in the eq curve. It would be possible to prevent ringing with parametric eq filters but until I have that implemented the convolution might (just might) be a safer option.

The frequency limits are a welcome improvement idea. It's a bit of an edge case so I'm not sure if I'll implement a safeguard against it and in any case it's not going to be a priority. I'll keep this ticket open as a reminder for it anyways.

**Comment by DeLub** [comment]
The 44.1kHz works fine. However, the 88.2 and 96kHz filters attenuate the sound to a very soft level. I’m sticking with the parametric EQ, that sounds quite good.

**Comment by jhon12346** [comment]
`var width1 = 5
var width2 = 5
var width3 = 5
var width4 = 5
var width5 = 5
var width6 = 5
var width7 = 5
var width8 = 5
var width9 = 5 
var width10  = 5

// type the width values of your model


var arr = [width1,width2,width3,width4,width5,width6,width7,width8,width9,width10 ]
  
arr.forEach(Q => { 
var sqr = Q*Q
var j = ((2*sqr + 1) / sqr )
var m = Math.log(1 + 1/(2*sqr) + Math.sqrt(j*j / 4 - 1))
var final = m/Math.log(2)
 console.log(final); 
} );`

for mac users change the width values and copy it and  run it [here](https://www.tutorialspoint.com/execute_nodejs_online.php)
