### ISSUE TITLE
Floats in GraphicEq strings

### ISSUE THREAD

**Issue by Pittvandewitt** [jaakkopasanen/AutoEq#151]
Hi,

It looks like during this commit https://github.com/jaakkopasanen/AutoEq/commit/5dc74db5756c268fe88d603d2d7882be6f5fa214 the GraphicEq frequencies were changed from ints to floats, with different values. Is this intended? If that's the case I'll need to make significant changes to my application. Previously the formula was the rounded result of 19,02672227 *  1.1 ^ band[index] , but that doesn't seem the case anymore.

**Comment by jaakkopasanen** [comment]
Not necessarily intended. I did change the sampling in FrequencyResponse class to use floats in the frequency data because using integers forces the sampling not to be purely logarithmic. This will cause issues in certain cases which assume the relative difference between two points remains the same.

This problem doesn't exist when using GraphicEQs in EqualizerAPO because EqualizerAPO resamples the data anyways. EqualizerAPO works with both integers and floats alike. I think I'll go back to having integers for frequencies in the GraphicEQ files.

**Comment by jaakkopasanen** [comment]
By the way there is a [hesuvi.zip](https://github.com/jaakkopasanen/AutoEq/blob/master/results/hesuvi.zip) in the results which contains GraphicEQ files organized by manufacturer. Maybe this would be of use for you?

I was also wondering why did you decide to use GraphicEQ files instead of the CSV files in the results? I would imagine parsing CSVs would have been easier than the custom format of the GraphicEQ files. CSVs in results have equalization column which is the ideal eq curve.

**Comment by jaakkopasanen** [comment]
GraphicEQ files have integer frequencies again. They don't have the exact same frequencies as before but the values are integers.

**Comment by Pittvandewitt** [comment]
I used the GraphicEq strings because they were easy to parse. They all contain the same band count (73) and all bands had the same frequencies.

With the commit you just made, this is the case again and it resolves the issues with the difference in frequencies.
Thank you for bringing the hesuvi zip to my attention too.

**Comment by jaakkopasanen** [comment]
Please do note that the new GraphicEQ files contain 127 bands instead of the old 73. I had this change in my mind for a while now and decided to add it here. Sorry if this causes inconveniences for you.

I had forgotten to update result indexes so the hesuvi.zip didn't have the new GraphicEQ files. It does now. If you already downloaded the hesuvi.zip for parsing, download it again.

**Comment by Pittvandewitt** [comment]
I adapted the code for my app with ease now all GraphicEQ files have the same frequencies again. Thank you!
