### ISSUE TITLE
Curves for modded headphones

### ISSUE THREAD

**Issue by pulpan977** [jaakkopasanen/AutoEq#158]
DIY Audio Heaven has some modding instructions for headphones and also response curves for the modded results. Could those be implemented in the database?

I'm most interested in these as I own both:
https://diyaudioheaven.wordpress.com/headphones/measurements/brand-superlux/hd681-evo/
https://diyaudioheaven.wordpress.com/headphones/measurements/brand-superlux/hd662-evo-2/

**Comment by jaakkopasanen** [comment]
There are some modded results included in the AutoEq. This depends if one of the supported databases has modded measurements then AutoEq will have results for these, not otherwise. DIY Audio Heaven is not supported in AutoEq and will not be since the measurements there are done on flat plate measurement system which is not good enough for this purpose.
