### ISSUE TITLE
Adding car profiles

### ISSUE THREAD

**Issue by MemeVR** [jaakkopasanen/AutoEq#173]
Hi,

Would it make sense to add profile of car's audio system?
It would then make sense to use something like the Wavelet Android app to stream filtered music to the car audio system over Bluetooth.

If it makes sense, how can it be done? Can individuals just contribute filters / profiles? based on recording of their car?

Thanks

**Comment by Pittvandewitt** [comment]
@MemeVR Speaker systems sound different on your position relative to them. Because of this, you can't take a measurement and expect it to be the same if you move the microphone a little and take a new measurement.
That said, in the future importing of custom AutoEq data in Wavelet may be supported and you can process a measurement of your own audio system if you're able to take one: https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9

Please close this issue.

**Comment by MemeVR** [comment]
Thanks. However in a situation where there is a single person in the car, and he is in the driver seat, it might be stable.
Thanks
