### ISSUE TITLE
[Feature Request] Preamp

### ISSUE THREAD

**Issue by xykrr** [jaakkopasanen/AutoEq#175]
Hi, I have a feature request- an option to modify the maximum gain of a target. This would be useful in the case of parametric eq software which doesn't have a preamp like in the case of the MiniDSP IL-DSP.
While an alternative solution would be manually making modified copies of the target csv files just for use with parametric eq software that lacks a preamp, I feel a command line preamp argument you can use per each tune would be very convenient.

**Comment by jaakkopasanen** [comment]
Hey there!

Do you mean that the parametric eq optimizer should produce filters which don't require any preamp? Implementing something like that is certainly not out of realm of possibilty but seems a bit odd that such a feature would be needed. I find it kind of unbeliveable that there would exist a paramteric equalizer which doesn't have preamp option. Are you sure it's not just automatic? Because it would be very easy for the equalizer to calculate the result frequency response and adjust preamp automatically. I of course don't know if MiniDSP IL-DSP does this or not.

**Comment by xykrr** [comment]
Yes- that is what I mean. Though, I agree it's pretty strange for a parametric eq to lack a preamp.
But, I can assure you that the software for the IL-DSP doesn't have a preamp. I'd send screenshots if I had access to the virtual machine I was using for the eq.
Since it's possible to greatly distort the sound without a preamp, I've actually goofed around seeing what music sounds like with distortion at different frequencies. It's kinda fun- maybe I don't want this feature :P

**Comment by jaakkopasanen** [comment]
I took a look at the user manual and datasheet. No mention about pre-amp. Odd device indeed. Too bad because other than that the little donge looks like a perfect companion for mobile devices.

Thanks for the idea. This feature might get implemented with the parametric eq rework. No promises though.

**Comment by xykrr** [comment]
You're welcome.
Okay, cool.

**Comment by jaakkopasanen** [comment]
`--preamp` is now implemented in AutoEq. I also replaced ES100 with IL-DSP in the hardware eq recommendations.
