### ISSUE TITLE
Oratory1990 Galaxy Buds+

### ISSUE THREAD

**Issue by Manu99it** [jaakkopasanen/AutoEq#185]
Oratory measured galaxy buds+. I would just know why that measurement is ignored, as stated [here](https://github.com/jaakkopasanen/AutoEq/blob/d0ad8ae003eff35740a4970ffb7b3bc6639b3433/measurements/oratory1990/name_index.tsv) when Oratory is preferred over rtings. Maybe because rtings named those "buds plus" and oratory "buds+". If this is an error please correct it or tell me why if it's intended, I'm curious. Thanks!

**Comment by NekoAlosama** [comment]
It seems that the measurements aren't in the project currently, as you can see in [oratory's measurement folder](https://github.com/jaakkopasanen/AutoEq/tree/master/measurements/oratory1990/data/inear) that there is only the measurements for the Galaxy Buds. Jaakko (the repo owner) needs to receive the Galaxy Buds+ results from oratory1990, then process them. This might take a while for this to happen, since (I hope) they are working on the parametric equalizer optimizer.

**Comment by Manu99it** [comment]
Thanks. Then I abuse this thread just to say thanks to jaakko and the other great people for this project!

**Comment by NekoAlosama** [comment]
Actually, ignore my previous comment. I only noticed the name_index.tsv file you linked just now and noticed that the Samsung Galaxy Buds Plus are ignored in the .tsv. Looking through the code in the data_crawler.py for oratory1990, it shows that some of oratory1990's graphs actually use the measurements from Crinacle! Since Jaakko (AutoEQ's dev) has Crinacle's direct measurements in .csv form, there is no need to extract the measurement's from oratory1990's graphs.

**Comment by NekoAlosama** [comment]
Now the question is why Rting's measurements are used over Crinacle's. Looking through the name_index.tsv for Crinacle, it shows that Crinacle doesn't have the measurements for the Galaxy Buds+. This means that either the measurements were so bad that they needed to be thrown out, or that they were accidentally deleted and AutoEQ's code thought that it must automatically move from oratory1990's graphs, if it has Crinacle mentioned, to Crinacle's measurements without checking if Crinacle actually has those measurements, and falling back to oratory1990's graphs.


This needs to be addressed.

**Comment by Manu99it** [comment]
For sure @jaakkopasanen can enlight us

**Comment by NekoAlosama** [comment]
@jaakkopasanen I think there is a case you missed in your crawler code.

**Comment by jaakkopasanen** [comment]
Sharp eyed users here. Indeed the oratory1990 crawler ignores measurements by Crinacle. In this case the raw measurement data for Buds+ is missing from Crinacle's raw data source so it never ended up in AutoEq. I added it through oratory1990 temporarily and informed Crinacle about this.

https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds%20Plus

**Comment by Manu99it** [comment]
Thank you man!

**Comment by NekoAlosama** [comment]
@jaakkopasanen Please tell us if and when Crinacle's measurements come through.

**Comment by NekoAlosama** [comment]
Shameless plug while we wait for Crinacle's measurements to come through: [here's my modified results for the Buds](https://github.com/NekoAlosama/AutoEQ-optimized/tree/master/results/oratory1990/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds%20Plus)

Note that the Galaxy Buds+ are very close to the Harman in-ear target.

**Comment by Manu99it** [comment]
Hi @NekoAlosama I've already noted your rebuilded repo. And I think @jaakkopasanen should provide at least also results with corrected bass. However anyone can download autoeq and build its own correction curve so 🤷🏻‍♂️.

And yep I know buds+ are very close to the Harman Target, I bought them for that

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/harman_in-ear_2019v2/Samsung%20Galaxy%20Buds%2B
