### ISSUE TITLE
Which one should i use? Peace Paramatric eq vs Equilizer APO's inbuilt paramatric eq

### ISSUE THREAD

**Issue by codeitout32** [jaakkopasanen/AutoEq#187]
I can't decide which one is accurate the readme clearly states to use peace parametric eq, but in the apo's editor shows a very weird graph

- I just want to know which one is superior to others so that I can stick to it.
- I've been using old sbaf version of Hesuvi plugin till now, and recently found new measurements of Harman 2019v2.
- I am trying to eq my sound magic E10.
- I'm a beginner doesn't know much about eq just trying to sound my earphone right.
- Also, can you tell me why the HeSuvi instructions are removed from the readme page? Just for curiosity.

### Peace Parametric Eq 
![peace paramatric eq](https://user-images.githubusercontent.com/68272313/87404655-0e343180-c5dc-11ea-9477-8d0f7d6486c7.PNG)

Above we can see the graph is very triangular.

![peace](https://user-images.githubusercontent.com/68272313/87404865-518ea000-c5dc-11ea-82e2-924bbf54ae0d.PNG)

But the peace UI shows good curves.

### Equilizer APO inbuilt parametric eq 
![paramatric](https://user-images.githubusercontent.com/68272313/87404957-72ef8c00-c5dc-11ea-9133-de25692f07e0.PNG)
The following graph also looks good but I don't know if it's correct or not. 
__This_ can be achieved if the parametric file is directly loaded in equalizer apo config file_

### Equilizer APO Graphic eq
![graphic eq](https://user-images.githubusercontent.com/68272313/87405325-eb564d00-c5dc-11ea-9f68-89f339b585e5.PNG)
Above graph is from equalizer apo's graphic eq file. 

Thanks,
Regards

**Comment by NekoAlosama** [comment]
If you are able to use EqualizerAPO's Configuration Editor, then you shouldn't really use Peace's parametric EQ and instead use the GraphicEQ. The GraphicEQ option should be more accurate to the actual equalization because it has more data points. If you are going to use GraphicEQ with Peace, just move the GraphicEQ step in the Configuration Editor around until it works.


The graphs in Peace and AutoEQ differ because your Peace configuration isn't actually using a parametric EQ. In Peace, the green 'EQ' button after the 'Gain Values', 'Quality', and 'Filter' toggles between GraphicEQ (on) and parametric EQ (off). Since that button is on, you are actually using a reduced version of AutoEQ's GraphicEQ and not using a parametric EQ. This is why the graph in the Configuration Editor is so triangular; it's only made up of a few points connected together. Peace's graph is just smoothed out. Switch that button off so that it becomes red, and the 'Quality' boxes will be able to be edited in Peace and the graph in the Configuration Editor using Peace should be the same as using the parametric EQ directly in the Configuration Editor.


I did not remove the HeSuVi instructions from the README nor remember what they said, but I assume the reason was that the HeSuVi equalizations were outdated and it's not able to update them itself. If you really want to use HeSuVi, download the [hesuvi.zip](https://github.com/jaakkopasanen/AutoEq/blob/master/results/hesuvi.zip) file in the results\ folder in AutoEQ and extract the 'eq' folder to HeSuVi's folder (which should be something like 'C:\Program Files\EqualizerAPO\config\HeSuVi', then replace the existing 'eq' folder with the extracted one). In HeSuVi, go to the 'Equalizer' tab and in the right section click on 'SoundMAGIC' and then click on 'E10.txt'. Then go to the 'Connection' tab and make sure the 'SoundMAGIC E10' button is toggled on and then click on the 'Get Suggestion' button to adjust the volume. HeSuVi may or may not work with Peace, depending on your configuration and order.


Just to plug in my own little fork of AutoEQ, I have a version of the [SoundMAGIC 10 equalization](https://github.com/NekoAlosama/AutoEq-optimized/tree/master/results/innerfidelity/innerfidelity_harman_in-ear_2019v2/SoundMAGIC%20E10) that might sound better than the one AutoEQ gives. You could also go the HeSuVi route with [this hesuvi.zip](https://github.com/NekoAlosama/AutoEq-optimized/blob/master/results/hesuvi.zip) from my fork. Try either method and tell me how it sounds (if you want).

**Comment by codeitout32** [comment]
> The graphs in Peace and AutoEQ differ because your Peace configuration isn't actually using a parametric EQ. In Peace, the green 'EQ' button after the 'Gain Values', 'Quality', and 'Filter' toggles between GraphicEQ (on) and parametric EQ (off).

![image](https://user-images.githubusercontent.com/68272313/87427277-2ddc5180-c5fe-11ea-98b9-c076dd21aaf2.png)

OMG! What a silly mistake I was doing till now, sorry you have to bother with that.


Anyway, I was using graphic eq in past but have read somewhere that parametric is better than fixed band eq. Are you sure Graphic EQ gives better results than parametric? Just wanna confirm.

Thanks for pointing out your fork I was already searching for some alternative presets. As the new 2019v2 measurements are fatiguing my ears a little that doesn't happen with old sbaf versions. 
Well, I'm kinda new to Github. So I wanna know is there can more versions of AutoEq like yours in forks.

Thanks

**Comment by NekoAlosama** [comment]
The normal order of the EQs are Convolution EQ > GraphicEQ > Parametric EQ > Fixed Band EQ. Reasons being: convolution EQ has 4410 or 4800 samples/data points for the frequency and gain for the equalization line in exchange for delay if used in EqualizerAPO; GraphicEQ is essentially the same as the convolution EQ but with only 127 samples/data points with no delay; Parametric EQ gives you a pretty good estimation of the equalization line but it focuses on the higher frequencies than the lower frequencies, sometimes giving lacking results; and, then there's fixed band EQ which is commonly used in the EQ settings for phones and media players, but they might fail when there is a dip or large gain between two frequencies (ex.: some headphones have a dip in the 9000 Hz frequency, which the fixed band EQ cannot fix since the two nearest adjusted frequencies are 8000 Hz and 16000 Hz)


The new equalization is fatiguing your ears because it has a gain of 4db at 10000 Hz to 15000 Hz compared to the previous target.
Previous target:
![image](https://user-images.githubusercontent.com/47763383/87431072-18dad080-c5b4-11ea-9e66-f50c368d39a7.png)

Current target (AutoEQ version):
![image](https://user-images.githubusercontent.com/47763383/87431108-2c863700-c5b4-11ea-91aa-a76cf99ed89e.png)

Current target (My version):
![image](https://user-images.githubusercontent.com/47763383/87431147-3c9e1680-c5b4-11ea-9cc8-665cc5c47b78.png)

Just lower your volume a bit more I guess.


There are other forks of AutoEQ in GitHub, but most of them are used for personal reasons. Look at [this page](https://github.com/jaakkopasanen/AutoEq/network) to see what forks are active (also I just found out that AutoEQ was updated yesterday, whoops on my fork).

**Comment by codeitout32** [comment]
Thanks now I will use Graphic eq without any hesitation, maybe use hesuvi instead of peace. It makes switching between presets faster.

Currently using your optimized preset but I can't say wats changed I'm the wrong person to answer that. But I can say bass and highs are lower in your version.

> The new equalization is fatiguing your ears because it has a gain of 4db at 10000 Hz to 15000 Hz

I've found that yours and original both produce clipping. I had to preamp to avoid clipping.

- Yours have to -12db instead of -10.78db
- Original has to -9.5 instead of -7.7db
(both are done in peace)

Maybe it helps in the fatiguing issue. Is there any other way to reduce it.


I can see that only you two are currently active in all forks keep it up, mate.

can you explain it a little what you trying to achieve in the optimized version?

Thanks, You've helped me a lot

**Comment by NekoAlosama** [comment]
In my version, the highs need to be raised, so it reduces the bass to compensate. The overall highs are lower since there are two main points that need to be at their highest, not a whole section.


On my end, using the -10.78db preamp with the parametric EQ directly in EqualizerAPO give no clipping. It actually reduces my peak gain to about -0.7db. Since you are using Peace, the 'Prevent Clipping' checkbox reduces the preamp further since that's what it's supposed to do. Even if you have no filters on, the 'Prevent Clipping' option will still reduce the preamp even though nothing is clipping (I think, I haven't used Peace in a while).


In AutoEQ, there are a few options and code you can tweak for better results. Most of what I will say are in the [README.md](https://github.com/NekoAlosama/AutoEq-optimized) of my project (just scroll down). There is a max_gain option in AutoEQ which  states at which level the equalization will stop and produce a flat line. The default is +6.0db for max_gain (look at the 'Previous Target' and Current target (AutoEQ version):' pictures above and see the line flattens at 6.0db). My version removes this max_gain option and allows the equalization to basically go up to any value (smoothly). The bass in my version is also increased by about >2.5 db compared to the default in order to match the Harman target better. There are a few subtler ones, like how the GraphicEQ by default sets 127 values from 20 to 19871, whereas my version sets 127 values from 20 to 19999.

**Comment by NekoAlosama** [comment]
Close the issue if you think your original question was answered please.

**Comment by codeitout32** [comment]
The area which fatiguing my ears can be caused because of some error as the flat response should not have tiring sound. What do you think that gain of 4db at 10000 Hz to 15000 Hz had caused because of some error or it is a problem?

OK, I think your version increases bass a little and in original I can hear more highs and mids. but it definitely decreases the dB.

**Comment by NekoAlosama** [comment]
The Harman target does not actually give a "flat" sound. It's more accurate to say that is has a "neutral" sound. A "flat" response is where all of the frequencies can play at the same absolute volume(?). This is not compatible with our ears, so we use the Harman target because it has the resonance that our ears need and it's just what people like.

AutoEQ is very stable; It would only break if you were really trying to. It should decrease the overall volume since the equalization has to reduce specific frequencies to make sure the audio signal is not clipping.

I don't have any problems on my end, especially no "tiring sound". What exact area is giving you problems? Like, is it the bass, low- and high-mids, treble, somewhere between?


You might notice that the Target and Equalized curves do not exactly look like the Harman target for in-ears.
![img](https://github.com/jaakkopasanen/AutoEq/blob/master/compensation/harman_in-ear_2019v2.png?raw=true)

This is because AutoEQ has to use innerfidelity's headphone measurements for your SoundMAGIC E10s. Since innerfidelity has difference couplets used for their measurements compared to the ones used for the creation of the Harman target, the curves have compensate for the couplet differences.
![img](https://github.com/jaakkopasanen/AutoEq/blob/master/measurements/innerfidelity/resources/innerfidelity_harman_in-ear_2019v2.png?raw=true)

This is why the gain between 10k Hz and 15k Hz is not an error or problem. It's part of the target curve used for this equalization.

**Comment by codeitout32** [comment]
Ok,
I am using your preset from now on.
Thanks for helping though.
