### ISSUE TITLE
Not really an issue but a question - correction factor goes into wrong direction (imo)?

### ISSUE THREAD

**Issue by codecollider** [jaakkopasanen/AutoEq#193]
Hi,

I was just trying out Sonarworks and after little recherche I found this git page. Seems to be an interesting project and a good alternative to sonarworks. 

I have a pair of Superlux HD668B and according to that frequency response there's a little boost at ~1 kHz:

https://www.rtings.com/headphones/1-4/graph#439/4011

In the parametric EQ correction parameter there is this line 

Peaking | 1093 Hz | 0.39 | 4.1 dB

i.e. a boost of 4 dB at ~1 kHz. Is there any explanation for boosting that range when there is no negative dip?
The sound character after final equalization is still considerably different to the sonarworks correction. 

Thanks for clarification.

**Comment by NekoAlosama** [comment]
AutoEQ recommends oratory1990's measurements and results over Rtings'. Oratory1990's results are shown [here.](https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/Superlux%20HD%20668B). Compare this to Rtings' results and graph [here.](https://github.com/jaakkopasanen/AutoEq/tree/master/results/rtings/rtings_harman_over-ear_2018/Superlux%20HD%20668B)

The 4 db gain is needed to correct the EQ curve, not to specifically neutralize dips. It's there so that with the addition of the other filters and preamp, the headphones will produce the right sound.

**Comment by codecollider** [comment]
Hi, 
thanks for the clarification. I will read at reddit and might ask more questions there. 

Cheers

**Comment by NekoAlosama** [comment]
Please close the issue if you have no more questions to ask here.
