### ISSUE TITLE
9 kHz Notch

### ISSUE THREAD

**Issue by jaakkopasanen** [jaakkopasanen/AutoEq#221]
9 kHz notch is being boosted up in the current smoothing scheme and it shouldn't. For example Sennheiser HD 800 asks for 9 dB narrow filter at 9 kHz which pretty much ruins the sound. Implement mechanism for avoiding boosting 9 kHz range, either in the equalize method or in the smoothing methods.

**Comment by fredoredo** [comment]
Hi Jaakko,
I was wondering, does the issue you mention here apply only to the HD 800's or if it applies to EQing in general? I'm kind of new to this stuff and I'm unsure if the 9kHz area shoudln't be messed with for a good sound profile. Asking because the headphone model I'm using is the FA-003, and it asks for +5.7 dB boost at ~9000kHz.
Cheers!

**Comment by jaakkopasanen** [comment]
It applies to almost all headphones because the 9 kHz notch is created by the measurement system, not the headphones themselves. Real human ears have this notch too so it should be there and should not be equalized.

I'm working on a solution which can avoid equalizing narrow notches and the 9 kHz one will be covered too. I still have some work to do but when I finalize the algorithm, I'm going to update all of the EQ profiles.

**Comment by jaakkopasanen** [comment]
The limited slope equalization algorithm with all the recomputed results were committed last Sunday. No more 9 kHz peak in the HD 800 equalizer frequency response and respectively the frequency response after equalization shows a deep notch at 9 kHz as it should.
![](https://raw.githubusercontent.com/jaakkopasanen/AutoEq/master/results/oratory1990/harman_over-ear_2018/Sennheiser%20HD%20800/Sennheiser%20HD%20800.png)
