### ISSUE TITLE
[REQUEST] EQ presets for portable speakers 

### ISSUE THREAD

**Issue by Freesail21** [jaakkopasanen/AutoEq#237]
I use a Sony GTK-XB90 Bluetooth speaker. Custom presents for Bluetooth speakers would be an excellent feature to add along with headphones.

**Comment by jaakkopasanen** [comment]
Speakers cannot be corrected with equalization in a similar way as headphones can be. Some improvements can be made if the full anechoic spinorama data is available, but it's not known at the moment how to automatically create an eq preset for a speaker based on the spinorama data. Moreover spinorama data is practically never available for Bluetooth speakers since those who have the required measurement system tend to focus on studio monitors and proper HiFi speakers.

**Comment by Freesail21** [comment]
Thank you for your reply, it's highly appreciated and a helpful response.
Great Dev support. Continue the good work my friend.
