### ISSUE TITLE
Zero value Q filter for Crinacle Beyerdynamic DT 770 80 Ohm

### ISSUE THREAD

**Issue by zenzero-2001** [jaakkopasanen/AutoEq#252]
**Describe the bug**
I noticed that one of the filters for Crinacle Beyerdynamic DT 770 80 Ohm has a Q value of zero:

[https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/gras_43ag-7_harman_over-ear_2018/Beyerdynamic%20DT%20770%2080%20Ohm]

I may be mistaken, but would this not imply an infinite bandwidth for this filter? I assume that this is not what we would want. Also the center frequency is beyond 20 kHz.

I don't actually own this headphone, but I saw this potential anomaly when browsing and thought I should report it.

**Comment by jaakkopasanen** [comment]
This is problematic. The Q values in the table are printed with fixed precision of 2 decimal points. I did some tests and I think the actual value "behind the scenes" would be something like 0.004, which rounds to 0.00 in the table. Due to how IIR filter are implemented (according to the filter cookbook), the bandwidth is far from unlimited in this case. The filter's gain ramps down to zero between 1000 Hz and 100 Hz. It's essentially a high shelf filter in this case. Definitely not ideal behaviour from the paramteric eq optimzer. In the next version I intend to limit the value range for Q to avoid these kinds of situation. Here the picture with Q of 0.004.
![Beyerdynamic DT 770 80 Ohm Parametric Equalizer](https://user-images.githubusercontent.com/8393524/103454051-ab993400-4ce8-11eb-9fa7-6e460126b6ff.png)

Center frequency can be beyond 20 kHz but not beyond the Nyquist frequency (half of sampling rate).

Thanks for reporting! I will close this issue and create a new one for the Q limits.
