### ISSUE TITLE
pandas 1.2.0 package could not be found

### ISSUE THREAD

**Issue by Dogway** [jaakkopasanen/AutoEq#260]
The module only exists for python 3.7 onwards and I'm on 3.6.8. I could get away with version 1.1.5 and every other module had no problems to install either nor it had any (visible) impact on the functioning of the scripts.

My question is in the Readme you encourage to install python 3.8. Is this a requirement for some reason? Maybe you could add some clarification or lower the minimum requirements?

**Comment by jaakkopasanen** [comment]
I've decided to opt for strict requirements because there has been too many problems. It's not possible for me to predict what happens with all the different possible combinations and the AutoEq users are not software developers so they don't have the skills to solve the issues themselves. So anyone who wants to use non-standard setup will have to figure it out themselves. This leaves two options for you: 1) install Python 3.8 or 2) install the required packages manually with the versions that are available for you and solve the potential conflicts also manually.

**Comment by Dogway** [comment]
Yes, I was wondering what is so necessary about pandas 1.2.0 being the minimum requirement when I managed to make it work with 1.1.5, unless you are telling me that it's not working as intended. Closing for now.
