### ISSUE TITLE
General ANC, On device EQ concerns (non specific but ref, Plantronics Backbeat Go 810)

### ISSUE THREAD

**Issue by carlosvigil** [jaakkopasanen/AutoEq#269]
In the results for the headset in the title there is no mention of the feature settings or if they're powered on. I understand this is automated but if the base or original FR was sourced from somewhere it should have mentioned these things: 

ANC on or off, ANC high or low, EQ bright or balanced, and the one that wipes those off the table, battery power on or off. If they're off then it can be assumed the connection was wired not BT, but they can also be used wired and ON for the other features.

For these headphones the recommended settings are based on Rtings, their discussion section discusses this confusion. They used ANC High and what can be assumed the Balanced EQ. Meaning they were powered on whether wired or not. For anyone concerned with why they're reading this, if you turn ANC off on these the low end kicks up 10db and messes with the usually great mid range.

**Comment by jaakkopasanen** [comment]
https://www.rtings.com/headphones/reviews/plantronics/backbeat-go-810-wireless

Doesn't say as far as I see.

**Comment by lukasubo** [comment]
@jaakkopasanen that's one thing that bothered me a bunch about rtings' reviews - I couldn't tell what settings they used. It seemed odd, because they're generally pretty transparent about their setups. Turns out the information _is_ there, in a box near the bottom of the "Sound" section of their reviews.

![image](https://user-images.githubusercontent.com/5761515/115952840-5b6ff880-a4b6-11eb-9e4a-decfec0594ac.png)
