### ISSUE TITLE
Is it possible to using AutoEq without nvidia gpu?

### ISSUE THREAD

**Issue by cs853120** [jaakkopasanen/AutoEq#276]
Sorry new to here
I can't install the AutoEq correctly without using tenserflow without using a nvidia gpu
Is there a alternative method?

**Comment by jaakkopasanen** [comment]
I'm afraid not. GPU is not required by any means but Tensorflow is.

**Comment by jaakkopasanen** [comment]
Perhaps my earlier message wasn't very clear so let me reiterate. GPU is not needed at all for AutoEq. I understand that the OP has some special configuration which makes it impossible to install Tensorflow without GPU but AutoEq itself doesn't need this.

I'm closing this issue since there's nothing to do on AutoEq side. Unfortunately it's not possible to support all the custom configurations people may have and therefore AutoEq is only guaranteed to work with standard configuration. Users who want to customize need to solve the problems on their own too.
