### ISSUE TITLE
Adding Microphone Equalization to the project

### ISSUE THREAD

**Issue by prank855** [jaakkopasanen/AutoEq#278]
**Describe the solution you'd like**
Adding a new section under AutoEQ to get a flat EQ on microphones.

**Additional context**
I have an AT2020 and the frequency response isn't necessarily very flat for a microphone. My first thought was to come here as maybe this project already handled microphones. I could not find anything in the main project or under issues, so thats why I'm submitting this feature request.

Example data of an AT2020 microphone found from [here](http://recordinghacks.com/microphones/Audio-Technica/AT2020)
![image](https://user-images.githubusercontent.com/5534076/109300862-59f6bc80-77f4-11eb-9412-97056ea53817.png)

**Comment by 1582343047** [comment]
hi，i am new here,but i think auto eq is good.
i have mi earpod,after doing eq,sounds better that before.
and i have questen ,there is no chart of mi
air2pro
i will send you ，pls do it，thanks



---Original---

**Comment by jaakkopasanen** [comment]
Thank for the idea, I like it. However I intend to keep AutoEq very much focused on headphones since pretty much everything about it has been designed for headphones.

I would suggest you to start your own project for microphones. You could use the autoeq-pkg repository as a dependency so that you don't have to write all the equalization stuff yourself.
