### ISSUE TITLE
PulseEffects Convolver

### ISSUE THREAD

**Issue by gustafla** [jaakkopasanen/AutoEq#282]
Hi. Sorry if this is a misunderstanding, but is the "Convolver" in PulseEffects usable for AutoEQ results wav files? It definitely does seem to work. If so, should we add instructions to use it in the readme?

**Comment by jaakkopasanen** [comment]
Would you mind giving a short description of how you got it working. I tried quickly to set it up just now but could not locate the WAV file in "Import impulse". Do you know what is the expected file extension?

**Comment by gustafla** [comment]
So I'm running PulseEffects 5.0.3 on Arch Linux. I enable the Convolver, then click on the waveform-button over the stereo width -settings. From that, "Import impulse" and browse my way to the wav files which are displayed by default. Wav-support might be a new feature, then?

**Comment by gustafla** [comment]
Looks like it was added in PulseEffects 4.7.2

**Comment by jaakkopasanen** [comment]
That explains it then. I'm running 4.7.1 because that's what I get when installing with `apt` on Ubuntu 20.04.

**Comment by gustafla** [comment]
I could submit a PR for the readme, adding a note that newer versions have the Convolver, but I'm mostly just hesitant because I don't understand if a Convolver and Convolution Equalizer are the same thing or not. They absolutely sound very similar to parametric EQ profiles I've imported from AutoEQ results in PulseEffects.

**Comment by alifarazz** [comment]
Here's how it looks on PulseEffects 5.0.3 using PipeWire:
![pulse](https://user-images.githubusercontent.com/32952512/112381638-6cd3b280-8d08-11eb-844a-b83600c6c02a.png)

**Comment by JaKasb** [comment]
I also successfully used PulseEffects on Debian and Ubuntu with Pulseaudio.
However I observed that the builtin convolver produces sound levels above 0dB.
The PulseEffect GUI shows a warning sign for clipping.
As a solution I applied a negative input gain of -6dB via the Input-Slider in the Convolver Plugin.

In the Equalizer Plugin, the import of parametric filter textfiles also works.
However I observed problems related to the language locale.
On my machine with German locale the import parser produces faults for floating-point parameters.
(The decimal seperator in German is the comma instead of a period)
E.g.: Q 0.9 -> Q 0.0

**Comment by lukasubo** [comment]
@JaKasb I noticed the same thing - the convolver will cause clipping without negative preamp.

**Comment by jaakkopasanen** [comment]
Thanks a lot everyone for the helpful discussion! I updated the instructions to recommend convolver instead of parametric eq.

**Comment by DianaNites** [comment]
What about the questions around negative pre-amp, and convolver needing more than parametricEQ? Usage instructions across the repo say only that parametricEQ needs a pre-amp adjustment, convolvers don't mention any?

**Comment by jaakkopasanen** [comment]
Good catch! I updated the description once more.
