### ISSUE TITLE
Does this work with speaker ?

### ISSUE THREAD

**Issue by godshades** [jaakkopasanen/AutoEq#29]
Does this work with speaker guys, I can't see any profile for speaker

**Comment by rpx91** [comment]
Since Toole's work has shown that a flat frequency response in an Anachoic chamber correspondence to listener preference in real rooms what I think you could do a similar thing with AutoEQ is EQ to flat. That's already available as a target option - like I recently asked about.

There are various [measurement sources](https://www.reddit.com/r/audiophile/comments/6gygyx/a_list_of_speaker_measurement_sources/). that post graphs from anechoic chambers. For example the [Sound Stage Network](https://www.soundstagenetwork.com/index.php?option=com_content&view=article&id=941:nrc-measurements-kef-ls50-loudspeakers&catid=77:loudspeaker-measurements&Itemid=153) has good graphs. These would need to be crawled.

There's also [NoAudiophile ](anechoic)who's doing his own measurements without an anachoic chamber but posts Equaliser APO configurations.

Room correction [above the transition frequency](https://www.audioholics.com/room-acoustics/room-reflections-human-adaptation) are thought to be doing more harm than good. In my setup I only ever EQ below 150hz and most of that is via Auddssey XT32 on the Subs. So an EQ that gets my loud speakers to flat in an anechoic chamber would seem like it's a good idea. Especially considering that some newer speakers like the KEF [LSX ](https://international.kef.com/products/lsx)and [custom builds](http://noaudiophile.com/Selah_Mejor/) are using active DSP to render a flat frequency response in a chamber. This would be a way to approximate that behaviour. Obviously the pre-built DSP loud speakers have amps for each driver and have much more granular control though.

You're probably busy enough with Impulficier and AutoEQ but a future fork perhaps!

**Comment by magicgoose** [comment]
See also: https://github.com/jaakkopasanen/AutoEq/issues/73

Since I did not want to use any nonfree software at this time, such as RoomEQWizard, I have tried AutoEQ instead and managed to achieve a pretty good effect (cancellation of peaks in the low range, like below ≈500 Hz).
This is not very convenient and there is _room_ for error, but if you don't have to do this often, this is certainly a way.
Procedure is roughly as follows:
1. Using e.g. Audacity or Tenacity:
  a. Record test tones (20 Hz .. 20 kHz) being played (in a loop) on the speakers (from another source, like your phone), separately for left and right speaker, using a measurement mic, placed somewhere near listening position
  b. Clean up / trim away any unwanted sounds/noise in the recordings which could affect the frequency graph
  c. Plot Spectrum (with a large FFT window), export, then edit it to make it a CSV flavor that AutoEQ will accept
2. Create impulses using AutoEQ CLI, separately for left and right speaker
  a. some important knobs to tweak are max gain, tilt, treble range; you'd want to set the treble factor to 0 so that it doesn't try to correct random stuff in higher frequencies
  b. generated .png files allow for a good first sanity check to see if the result is completely off or maybe not
  c. for speakers which don't go all the way down to 20Hz, you might need to tweak the target curve by reducing the lowest frequencies which the speakers cannot play, so that AutoEQ won't try to amplify those (which could cause issues, or at best, it's useless)
3. Combine 2 impulses into one stereo impulse, could be done manually in Audacity or Tenacity, or could be scripted, I didn't need more than 3 attempts so I didn't bother scripting this

Let me know if you'd like more detail about any of that.
