### ISSUE TITLE
Repository size

### ISSUE THREAD

**Issue by rvalles** [jaakkopasanen/AutoEq#3]
Huge. Why not keep the pregenerated presets in a different repository or elsewhere?

**Comment by jaakkopasanen** [comment]
This is a fair point. However I think the ease of use for the users who are just fetching pre-calculated results for their headphones is more important. Besides the zip is 62MB, which I think is less than the dependencies.

**Comment by mhtvsSFrpHdE** [comment]
@jaakkopasanen 

Today the main branch size is keep increasing.  
When I do a fresh git clone,  
it takes me more than 20 minute due to my connection speed.  
The download size is 1.43 GB  
Most of them are binary files(*.wav, *.png),  
This is not worth.  

Although git clone --depth=1 and git fetch --depth =1 have less download size,  
but they can't always update the latest code for a unknown reason,  
(some of the commit on remote doesn't download to local)  
only the standard git clone can do that.  

I'm imagine a separate repo that only include source code and data,  
but no pre-result included.  
If you feel that hard to manipulate two repo,  
there's a open source tool called "Free file sync",  
It can do selective file sync between two folder.  
Thus you can work in standard repo,  
then update only the source code and data  
from your standard repo into the new "No binary" repo.  

If you don't have that much free time to do that just forgot what I'm talking about.^_^

**Comment by jaakkopasanen** [comment]
There's code only repository nowadays. https://github.com/jaakkopasanen/autoeq-pkg

If you need a repo with code and data but no results you can fork autoeq-pkg and add data from original AutoEq. I don't think I'm going to maintain a third repo.

**Comment by mhtvsSFrpHdE** [comment]
@jaakkopasanen Wow, That's pretty cool
