### ISSUE TITLE
Can someone create an equalizer preset for the Sound BlasterX Katana?

### ISSUE THREAD

**Issue by HolySoap** [jaakkopasanen/AutoEq#304]
I searched the whole day for something, anything, but everything is related to Creatives own rubbish software that I can't use on Linux. Thanks to [Igor's Lab](https://www.igorslab.de/soundbar-subwoofer-messungen-sound-einstellungen/2/) I found probably the only frequency response to these **loudspeakers/soundbar with subwoofer** to create a numeric CSV file ([Dropbox link](https://www.dropbox.com/s/5r048c03m0azoy2/Sound%20BlasterX%20Katana%20%28SBX%20disabled%29.csv?dl=0)).

It would be really nice if someone with knowledge can help me out.
Thanks in advance.

**Comment by jaakkopasanen** [comment]
AutoEq is not meant for room or speaker correction. Speakers are corrected based on in-situ measurements in the room and typically only the low end is corrected because the in room measurements don't tell the whole picture above transition band (300~700 Hz). Similarly a on axis (I'm assuming that's what it is in Igor's Lab) frequency response isn't enough to produce correction for speakers. That requires a full spinorama measurement where the speaker has been measured in anechoic space from all possible directions.

If you still insist on trying to create eq profile for this with AutoEq, you can follow the guide linked in the beginning of the results page. I'm closing this issue since issues are not the place for these requests.
