### ISSUE TITLE
Questions about inear, compensation and earbud

### ISSUE THREAD

**Issue by Banswidth** [jaakkopasanen/AutoEq#332]
Hello. First of all I would like to say thank you to the developer of this project, this really turned my headphone into something way better.

I have 3 questions to ask, and they are as follows:
**1.** Is it possible to use a sound signature of IEM on a headphone (i.e. is it possible to make a headphone sound like an IEM)? I know that they have different compensation targets, but, just out of curiosity, are headphones going to sound like IEMs if I correctly follow all the steps in the guide?
**2.** Regarding earbuds, why are they using the same harman target as in-ear monitors? I assume that they interact with human ears differently (e.g. Apple AirPods 2).
**3.** The guide mentioned that compensation curves for rtings, innerfidelity etc. were altered according to the difference between oratory1990 and their measurements. If that is the case, can I say that all measurements from different parties are of the same accuracy (for users) beacuse when their measurements are different, their target curves are different as well, resulting in the same 'error' column as oratory1990's measurements.

Thank you very much!

**Comment by jaakkopasanen** [comment]
1. Yes. The sound signature is the headphone's deviation from the target so if the target has been appropriately selected for the headphone used as sound signature, you can use that with any headphone.
2. Earbuds are a wild, wild west since the frequency response changes dramatically based on the placement. One could argue that you shouldn't even produce eq settings for them based on measurements. IEM target is my best guess for what should be used with earbuds but that's really it, a guess. They do have lower bass shelf in the pre-computed results though, that's because earbuds cannot reach the 10 dB shelf.
3. That's not unfortunately how it works. Different measurement systems have different acoustic imbedances and therefore you don't get the same deviation for different headphone models. The target curves are a statistical mean but that doesn't guarantee results for an individual headphone. Every headphone model actually requires it's own calibration curve but obviously that isn't possible to do.
