### ISSUE TITLE
ThieAudio Monarch seems to not match up with the updated measurement by Crin

### ISSUE THREAD

**Issue by Manueljlin** [jaakkopasanen/AutoEq#338]
I was checking some of Crinacle's graphs and comparing it to the AutoEQ results and the bass seems off in the measurements. I'm suspecting the measurements from here [are from the unboxing on the incorrectly built unit](https://crinacle.com/2020/07/29/thieaudio-monarch-unboxing/). He later remeasured it for the Monarch/Clairvoyance review when they sent over a second unit. Not sure if that was updated on the CSVs from Drive as I'm on a lower patreon tier, but it wasn't updated either here or there.

These are the graphs from his web tool with the Harman IE 2019 v2, compared to the ones on here. I tried to make these be as similar as possible on the db vertical axis despite the different aspect ratio.

## Stock Monarch

![monarch](https://user-images.githubusercontent.com/11275573/131880176-68df46ab-0976-4ef9-b231-b2e7d384ad9f.png)
![ThieAudio Monarch](https://user-images.githubusercontent.com/11275573/131880397-86443dcc-4607-4b7d-8a98-c52a7796d3e2.png)

These have a 5db bass difference

## 20Ω adapter

![monarch_20](https://user-images.githubusercontent.com/11275573/131881042-70682b52-4c08-415a-a66d-91ccf1f069cc.png)
![ThieAudio Monarch (200 ohm resistor)](https://user-images.githubusercontent.com/11275573/131881071-7ccae9cb-f8f5-4778-93cf-1ad520b1c23c.png)

These look pretty much the same. I'm guessing the 20Ω and 100Ω measurements are from the review and not the unboxing.

**Comment by jaakkopasanen** [comment]
Thanks for reporting! The problem was that there are measurements for Monarch and Monarch S2 (as in sample 2). I don't check these things manually but rather assume the different samples should be averaged as sometimes people measure and publish multiple different correctly working samples. In this case there was no way for me to catch this, so thank you!

Looks to be correct now:
- https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/harman_in-ear_2019v2/ThieAudio%20Monarch
- https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/harman_in-ear_2019v2/ThieAudio%20Monarch%20(20%20Ohm%20resistor)
- https://github.com/jaakkopasanen/AutoEq/tree/master/results/crinacle/harman_in-ear_2019v2/ThieAudio%20Monarch%20(100%20Ohm%20resistor)
