### ISSUE TITLE
96000hz Arctis Pro GameDAC

### ISSUE THREAD

**Issue by Aex6** [jaakkopasanen/AutoEq#344]
Is there and can there be a 96000hz wav file please? DAC supports it and I wanna use it, but dont know how to do this wav file myself except slapping it into EQ APO and calling it a day. 

Many Thx

**Comment by jaakkopasanen** [comment]
The precomputed results don't include 96 kHz files because there's no benefit from using higher sampling rates than 44.1 kHz or 48 kHz. If insist on using 96 kHz, you need to generate one yourself with AutoEq. See the [usage instructions](https://github.com/jaakkopasanen/AutoEq#equalizing) and especially `--fs` parameter.
