### ISSUE TITLE
Equalizing Power for Treble Frequencies

### ISSUE THREAD

**Issue by Banswidth** [jaakkopasanen/AutoEq#363]
I found out from the result graphs that treble frequencies peaks and dips were not fully equalized (I know this is because of resonances and difference in human ears, as mentioned in the guide). However, when equalizing an IEM to sound like another, the decrease in power of treble equalization makes some of them feel inconsistent (i.e. the treble energy does not pair/go along well with upper mids as a whole), which causes some timbre issues.

I have tried to play around with --treble_f_lower=19999, --treble_f_upper=20000 and --treble_gain_k=0 so as to maintain equalizing power up to 19999 Hz. It worked to some extent, but when the targets' and original IEM's peaks or dips were very close to each other (e.g. 8k and 9k), the equalizing power was still not as powerful to precisely equalize them to the target. Is there any way that I can equalize one IEM to the EXACT frequency response of another IEM?

Thank you so much developer.

**Comment by angelooo18** [comment]
Same problem here

**Comment by jaakkopasanen** [comment]
This could be because AutoEq has maximum slope steepness for the equalizer frequency response. Very narrow spikes in the equalizer can cause ringing and are therefore better to be avoided. There is no parameter to control this.

Can't say for certain this is the case without seeing the graphs.

**Comment by sabreenrz** [comment]
He's referring to situations like this one, where I tried to tune my KZ ZSX to the FR of a 64Audio U12:
![KZ ZSX](https://user-images.githubusercontent.com/56247765/146896901-71926036-4f6b-48c3-9413-0c0a34d5df63.png)
Notice, the lack of equalization on the 7K and 19Kish peak. I've already set the max gain parameter to a very high value, it doesn't make a difference. 

Or here, when I tried to tune my Hifiman HE35X to a the FR of the Hifiman HE1000,
![HIFIMAN HE35X](https://user-images.githubusercontent.com/56247765/146898073-9567cc63-052d-48fe-8585-091f149542f4.png)
And it missed the 9K peak there completely.

Anyway around this? That being said, all things considered, the fact that it can be brought close to 95% of the target FR is nonetheless quite impressive.

**Comment by jaakkopasanen** [comment]
This is all intentional. You need to understand that equalizing the measured frequency response more accurately in the highest frequencies won't make the headphones sound more like the target headphones. The measurement system will report different frequency response in the high frequencies as what your own ears will perceive due to the individual shape of your pinnae and ear canals and the acoustic imbedance of your ears. Because of these reasons, AutoEq tries not to equalize upper treble too precisely as it can do more harm than good.

**Comment by soyelmismo** [comment]
sorry for necroposting... what in those cases of some kind of microphone calibration?

![image](https://github.com/jaakkopasanen/AutoEq/assets/123757457/e9032252-768d-4a5d-807b-519edde73dfc)


this is the mic audio with exported convolution eq... treble cant be precise in the AutoEQ web version, i know it can be fixed with some post-process but it would be better having everything in 1 convolution file to save some cpu.

![image](https://github.com/jaakkopasanen/AutoEq/assets/123757457/3007dc5c-0019-4e0d-b383-ff07060c09e0)
