### ISSUE TITLE
Show Post-EQ score

### ISSUE THREAD

**Issue by lewisl** [jaakkopasanen/AutoEq#368]
Some headphones equalize well--they have the driver capability to raise bass or treble or the reverse. Some lack the inherent physical properties to change much. Some jiggle all over the place and it's not possible to provide adequate correction. 

While some listeners would say that needing to EQ a headphone to make it sound "decent," "OK" or "really nice" is cheating, no one who is interested in AutoEQ or manual EQ adjustments would be in that camp.

So, the post EQ scores are relevant and available--if you go looking at every PDF.

Want some help.  By this point text recognition in pdf's is good enough that the task could be automated.

Anyway, just a suggestion...

**Comment by jaakkopasanen** [comment]
Post-eq scores depend on the eq method and maximum gain so it's not possible to provide a single value that represents the only truth. With convolution eq and unlocked maximum gain, almost any headphone will be able to achieve full score and the remining error is due to the eq filter ringing prevention mechanism in AutoEq (a good thing). The biggest weakness in Harman preference scores is the lack of consideration for ringing peaks so the post-eq score wouldn't really tell anything in this case. Moreover the score is not tremendously helpful above 90 or so, a score which all headphones can achieve with eq. For these reasons I haven't and won't implement post-eq score.

**Comment by lewisl** [comment]
Fair enough. Oratory1990 shows the post EQ scores in his pdfs and he would also largely agree with your basic point that over 90 is very good. You might still hear some differences depending on where the post EQ discrepancy is and how sharp it is. But a score based on averaged differences across the entire frequency spectrum could not reveal such differences.

Good call.

From: Jaakko Pasanen ***@***.***>
Reply-To: jaakkopasanen/AutoEq ***@***.***>
Date: Saturday, November 20, 2021 at 11:18 PM
To: jaakkopasanen/AutoEq ***@***.***>
Cc: Lewis Levin ***@***.***>, Author ***@***.***>
Subject: Re: [jaakkopasanen/AutoEq] Show Post-EQ score (Issue #368)


Post-eq scores depend on the eq method and maximum gain so it's not possible to provide a single value that represents the only truth. With convolution eq and unlocked maximum gain, almost any headphone will be able to achieve full score and the remining error is due to the eq filter ringing prevention mechanism in AutoEq (a good thing). The biggest weakness in Harman preference scores is the lack of consideration for ringing peaks so the post-eq score wouldn't really tell anything in this case. Moreover the score is not tremendously helpful above 90 or so, a score which all headphones can achieve with eq. For these reasons I haven't and won't implement post-eq score.
