### ISSUE TITLE
Biasnet equalizer 

### ISSUE THREAD

**Issue by bhack** [jaakkopasanen/AutoEq#390]
I don't know if you could be interested in

Deep Optimization of Parametric IIR Filters for Audio Equalization:
https://arxiv.org/abs/2110.02077

**Comment by jaakkopasanen** [comment]
It's an interesting paper but as I understand it, the solution is a neural network which is optimized separately for each frequency response measurement. This is unfortunately so interesting for AutoEq as there already is a comparable method of automatically finding parametric equalizer parameters. What I am interested to find is a method which can estimate the parameters in a single forward pass of a pre-trained neural network. This would enable the estimation of the parameters in the range of a few milliseconds instead of several seconds or even minutes. This kind of speed would be necessary to serve AutoEq as a real-time web app.

**Comment by bhack** [comment]
You can try to take a look at:

https://dafx2020.mdw.ac.at/proceedings/papers/DAFx2020_paper_7.pdf
