### ISSUE TITLE
[Headphone Requests] CCA CRA

### ISSUE THREAD

**Issue by Josde** [jaakkopasanen/AutoEq#412]
Measurements:  
https://crinacle.com/graphs/iems/cca-cra/  
https://www.headphones.com/community/reviews-learning-and-news/cca-cra-review-bass-basked-glory

**Comment by Suznyan** [comment]
https://github.com/jaakkopasanen/AutoEq/issues/398#issue-1092426986

**Comment by Suznyan** [comment]
https://github.com/jaakkopasanen/AutoEq/issues/398#issue-1092426986

**Comment by foldfree** [comment]
i see that a lot of new measurements from websites are not in the repo, is it possible to update the /results/ folder?

**Comment by jahmad1234** [comment]
would be great to have this iem added  - thanks

**Comment by RaulMARK17** [comment]
A temporal solution:
https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9

Do it yourself, it isn't difficult, you just need python 3.8 the libraries and download the repo.

Or, send me the frequency response graph (average of left and right) and I cand do it for you, but, tell me what compensation you want

**Comment by jahmad1234** [comment]
Thank you for the link and taking the time to reply.

Wasn't sure which response graph to use as I've seen a few online eg [Crinacle](https://crinacle.com/graphs/iems/cca-cra/), [Crackhead](https://www.head-fi.org/showcase/cca-cra.25622/) and from [Headphones.](https://www.headphones.com/community/reviews-learning-and-news/cca-cra-review-the-best-deal-in-audio)  I'm not sure which to use or even if it matters that much.   

I'll use the Harman target initially and then maybe have a look at some of the other options later.

Since I posted a few days ago I've done the setup of python +;libraries and will give it a try.  Thanks again for your generous offer but I think I should learn to do this for myself so I can get used to the tools/process.

**Comment by RaulMARK17** [comment]
I have a KZ ZSN Pro X. 
And I don't like the results, I recommend you to try with "Auto Eq in ear target".

In my case, it improved the mids. I feel everything is more clear

**Comment by jenabaivab** [comment]
@RaulMARK17 sorry for the random ping, but can you create an EQ for the audio hekili? While it's quite similar to the audio lokahi, the bass is boosted way too much on the hekili and I want a little more room for mids, since they are very easily overpowered by the drums on certain tracks.
 You can see here: 
https://hbb.squig.link/?share=Lokahi,Audio_Lokahi_8+1

**Comment by RaulMARK17** [comment]
Try this:
https://tecnm9-my.sharepoint.com/:f:/g/personal/le18081484_merida_tecnm_mx/EidJXA-7EeNGj7Yfnvyg-joB7mxacLMbYEy4oegyT8V4bw?e=F1erGz

**Comment by RaulMARK17** [comment]
Try this:

[Hekili](https://tecnm9-my.sharepoint.com/:f:/g/personal/le18081484_merida_tecnm_mx/EidJXA-7EeNGj7Yfnvyg-joB7mxacLMbYEy4oegyT8V4bw?e=F1erGz)

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/blob/master/results/crinacle/harman_in-ear_2019v2/CCA%20CRA

Enjoy!
