### ISSUE TITLE
[Headphone Requests] AKG K371bt

### ISSUE THREAD

**Issue by buscon** [jaakkopasanen/AutoEq#413]
the AKG K371bt has not been measured by anyone yet.
I could not find any frequency response graph anywhere on the internet, even in the AKG manual.
So I used the frequency response diagram offered by Sonarworks SoundID Reference and followed your [online guide](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9) to generate the results.

As a reference here is the frequency response of Sonarworks:
https://www.dropbox.com/s/k1in8w8pndu5c73/371bt_SoundID_fr.png?dl=0
and here are my results:
https://www.dropbox.com/sh/fkn47i7eid8axi9/AADx7T-Td41BGbyAmhPKcdfua?dl=0

Here are the settings I used:
python autoeq.py --input_dir=mydata/K371bt/ --output_dir=my_results/K371bt --compensation=compensation/zero.csv --equalize --parametric_eq --max_filters=10 --ten_band_eq --convolution_eq  --standardize_input --fs=48000

I think they are good results, maybe they can be added to the official list of results?

**Comment by jaakkopasanen** [comment]
AutoEq only supports the select sources because it will be practically impossible to ensure any form of consistency when the measurements come from uncontrolled sources. Therefore your results won't be added.

I would venture to guess that K371bt is the same as the non-Bluetooth version so you might want to try with those results too.
