### ISSUE TITLE
Why do headphone that are identical in construction have different results?

### ISSUE THREAD

**Issue by maeries** [jaakkopasanen/AutoEq#426]
For example the Sennheiser HD 25 and HD 25 Plus are the same headphone, the Plus just comes with more accessories. Yet the results are quite different. Also so HD 25-1 II and HD 25-C II are afaic the same exept for the cable.

So why to seemingly identical headphones have different results?

**Comment by jaakkopasanen** [comment]
Even the different units of the exact same headphone model have differences due to manufacturing tolerances. The different models here are different units and in some cases can be even measured on different measurement systems which would produce even greater differences. This is unfortunately something I cannot control as I don't measure headphones myself so there's nothing that can be done other than advicing the users to try them all and sticking with what sounds best to you.
