### ISSUE TITLE
GiveUp: Preamp support

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [jaakkopasanen/AutoEq#44]
In the early version (near 1/29/2019),  
the following command generated result folder will contain Preamp value in README.MD,  
like:  
```
python .\frequency_response.py --input_dir="%inputDir%" --output_dir="%outputDir%" --compensation="%compensationFile%" --equalize --show_plot --max_gain %MAX_GAIN% --treble_max_gain %TREBLE_MAX_GAIN%
```  

```
...
### EqualizerAPO
In case of using EqualizerAPO without any GUI, replace `C:\Program Files\EqualizerAPO\config\config.txt`
with:

Preamp: -12.3dB
GraphicEQ: 21 0.0; 23 6.2; 25 5.8; 28
...
```
  
With this version, the generated result will not have "Normalize response".  
And in new version, the generated result have "Normalize response" by default,  
and not a preset Preamp value out there anymore.  

I think this is relatively bad idea,  
because you can imagine, a user across those command line commands,  
and finally generated his exciting eq settings,  
hi might be click on the power button at the left of the GraphicEQ,  
to switch the GraphicEQ on and off to try to hear the difference between the two status.  
By default Autoeq have a 6db limit,  
for some reason we can release the limit,  
in this case, the switch action will result in a maximum to the release value(e.g 24 db)  
volume level difference.  
**This have a risk to damage hearing.**  
The early version, with Preamp still on,  
simply switch GraphicEQ off will not get the volume level change,  
so it's much more safe than "Normalize response".  

I understand that maybe a unknown reason to do the change,  
but can we add a argument to use old method to provide result?  
That would be handy.

**Comment by Avilad** [comment]
It seems to me like the new versions of AutoEq just add the preamp value to each point of the EQ curve, which has effectively the same result, while potentially supporting tools that can't deal with the Preamp setting.

**Comment by mhtvsSFrpHdE** [comment]
@Avilad The price is a user can not easily one-click to hear the difference.  
Different target has different maximum gain value,  
Mix them together will lose the ability to make sure them at same volume level.

**Comment by jaakkopasanen** [comment]
It's possible to achieve even better volume matching than before simply by setting two preamps manually in EqAPO config and toggling both positive preamp and graphic eq:
```
Preamp: -4dB
Preamp: 3dB
GraphicEQ: ...
```
This way you can set the positive preamp to a level where both equalized and unequalized have similar perceived loudness. Perceived loudness will not be the same when the preamp is simply set to highest positive gain as it was before so the results weren't really ready for comparison aginast unequalized sound. Negative preamp should always be of greater magnitude than the positive preamp to avoid clipping.

It's even possible to put the positive preamp and GraphicEQ (parametric eq filters) in a same file and and include that in the main config if toggling two lines seems like unreasonable effort.
```
# config.txt
Preamp: -4dB
Include: C:\Program Files\EqualizerAPO\config\my_results.txt
```
and
```
# my_results.txt
Preamp: 3dB
GraphicEQ: ...
```

**Comment by mhtvsSFrpHdE** [comment]
@jaakkopasanen I use script to replace entire config.txt in order to compare multiple profile.  
I carefully read your example, but haven't got any idea about it.  
I can't understand what are you talking about, that how do you match the volume level.  

No, the problem is, after "Normalize response",  
it's not possible to revert the status back to the early stauts.  
In the early version we know that profile "A" have preamp -11.6 db,  
the profile "B" have preamp -8.6 db,  then just set profile "B" preamp to -11.6 db,  
this can match the volume level.  

Now we lost the preamp value.  
We don't know to get the eq settings to work, how much preamp value is actually priced.  
We don't know how many different between profile "A" and "B" anymore.  

Fine, there maybe a math algorithm to carefully retrieve the preamp value from such a mess,  
but... you know...  
the early method just work fine and easy to understand.  
I'm not deny the new method's value,  
but just keep the old method exist at the same time, even if put it into a hidden launch argument...

**Comment by jaakkopasanen** [comment]
The two volumes were not matched even before this change. Maybe they were usually in the same ballpark but definitely not close enough for doing serious comparisons. Different frequencies don't affect perceived volume equally so the perceived loudness depends on the actual frequency response as well as the preamp value. Perceived loudness has never been compensated by AutoEQ so the sound pressure levels have never been comparable. Not now and not before. Bringing preamp back won't give you equal volumes for different profiles as seem to you think.

Only way currently to achieve equal loudness levels is to adjust preamp manually. Although even this won't give very accurate results and one could argue if the whole task is meaningful anyways. But to get best results one needs to use GraphicEQ which has preamp built in (maximum gain at any frequency is 0.0 dB) and then add positive preamp gain to bring the perceived loudness level to match perceived loudness level without equalization. This of course will introduce clipping and therefore there needs to be a second preamp gain with negative value that overcomes the positive preamp.

In other words:
- GraphicEQ will lower the perceived loudness because it has negative or zero gain for all frequencies
- Positive gain preamp is added to combat lowered loudness
- Negative gain preamp is added to combat clipping introduced by positive gain preamp
- Only positive gain preamp and GraphicEQ lines are toggled on and off when comparing

This is the case when comparing one profile against no profile. `config.txt` would look like this:

Equalization enabled:
```
Preamp: -6dB
Preamp: 6dB
GraphicEQ: 21 -2.9; 23 -3.0; 25 -3.1; 28 -3.4 ....
```

Equalization disabled:
```
Preamp: -6dB
#Preamp: 6dB
#GraphicEQ: 21 -2.9; 23 -3.0; 25 -3.1; 28 -3.4 ....
```

So you see the negative preamp is activated in both cases to keep the volume level same for both.

Now if you want to compare two profiles you need to do the same but you'll only need one negative preamp and that must be greater than either of the positive preamps.

Profile A enabled:
```
Preamp: -8dB

Preamp: 6dB
GraphicEQ: 21 -2.9; 23 -3.0; 25 -3.1; 28 -3.4 ....

#Preamp: 8dB
#GraphicEQ: 21 -2.2; 23 -2.3; 25 -2.6; 28 -3.3 ...
```

Profile B enabled:
```
Preamp: -8dB

#Preamp: 6dB
#GraphicEQ: 21 -2.9; 23 -3.0; 25 -3.1; 28 -3.4 ....

Preamp: 8dB
GraphicEQ: 21 -2.2; 23 -2.3; 25 -2.6; 28 -3.3 ...
```

Both profiles disabled:
```
Preamp: -8dB

#Preamp: 6dB
#GraphicEQ: 21 -2.9; 23 -3.0; 25 -3.1; 28 -3.4 ....

#Preamp: 8dB
#GraphicEQ: 21 -2.2; 23 -2.3; 25 -2.6; 28 -3.3 ...
```

Positive preamp values must be adjusted by ear, individually for each profile. In the example above profile A doesn't attenuate frequencies as much as profile B and therefore profile A has lower value for positive preamp. One must listen to compare loundess when equalization is enabled vs when it is not and keep adjusting the positive preamp value until both sound as loud.

You'll start with `Preamp: 0dB` and will probably notice that volume is higher when equalization is disabled. Then you increase the preamp value to for example `Preamp: 3dB`, listen again to check if the volumes match. You keep adjusting and listening until you think volume is the same with or without equalization. And to repeat: both positive preamp and GraphicEQ line must be toggled on or off together and negative preamp must be kept enable at all times.

It's a good idea to set the negative preamp in the beginning to so high value that you don't positive preamp value won't grow higher. This ensures you'll have same volume when equalization is disabled on each iteration. You could for example set the negative preamp in the beginning to -20dB.

And once again: bringing back the preamp in AutoEQ won't give you equal loudnesses for different profiles, only the method described above will.

**Comment by mhtvsSFrpHdE** [comment]
@jaakkopasanen Thank you for the explain.
