### ISSUE TITLE
New app on Android

### ISSUE THREAD

**Issue by Jos158v** [jaakkopasanen/AutoEq#447]
Poweramp Equalizer is paid app but it let you use a Parametric Equalizer on Android :)
Hope you add it on [README.md](https://github.com/jaakkopasanen/AutoEq#readme)

**Comment by jaakkopasanen** [comment]
This has been discussed already in #387 and I decided not to include it.

**Comment by RubioJr9** [comment]
@jaakkopasanen You should reconsider. They made the app free since it was last discussed. While there is quite a large list already, it's the only non-root, system-wide, parametric EQ on android.

While I understand wanting to keep the list short, I'd argue this one is better than the rest. Had I not found this app, I was about to purchase a Qudelix 5K for parametric EQ.
