### ISSUE TITLE
[Headphone request] HyperX Cloud Alpha Wireless

### ISSUE THREAD

**Issue by Minnona** [jaakkopasanen/AutoEq#482]
Hey, can eq settings be added for this headset if possible? There's a [review on rtings.com](https://www.rtings.com/headphones/reviews/hyperx/cloud-alpha-wireless).
Thanks!

**Comment by jaakkopasanen** [comment]
https://github.com/jaakkopasanen/AutoEq/blob/master/results/rtings/rtings_harman_over-ear_2018/HyperX%20Cloud%20Alpha%20Wireless

Enjoy!

**Comment by Minnona** [comment]
Thank you!

**Comment by Minnona** [comment]
@jaakkopasanen hey, I see you renamed HyperX Cloud Alpha into wireless model, these are 2 different models with different FR profiles. Just double checking if everything's correct 😃 
https://www.rtings.com/headphones/reviews/hyperx/cloud-alpha-wireless
https://www.rtings.com/headphones/reviews/hyperx/cloud-alpha

**Comment by jaakkopasanen** [comment]
I had originally named the "Cloud Alpha Wireless" as "Cloud Alpha" because Rtings has a bad habit of adding "wireless" or "tws" or whatever at the end of the headphone names so I need to remove those. I thought this was the case here too. Now the "Cloud Alpha" and "Cloud Alpha Wireless" are correct in AutoEq.
