### ISSUE TITLE
Narrow Dip Treatment: Close and Open

### ISSUE THREAD

**Issue by libeako** [jaakkopasanen/AutoEq#506]
Have you considered the morphological 'close' and 'open' operations for avoiding the working on narrow dips and peaks? I just read your report about this topic [on Reddit](https://www.reddit.com/r/headphones/comments/l9g1f4/avoiding_dips_when_equalizing_headphones/) and immediately those morphological operations came into my mind.

I do not know whether it is good for you or not. Just an idea.

**Comment by jaakkopasanen** [comment]
I was not aware of those operations before you brought them to my attention. After some consideration, I don't think they're going to help. Perhaps the algorithm could have been made somehow using those operations but there's always a lot of edge cases to be caught so it's also possible they might not. And since the current one works well, I'll leave thing as they are.

Thanks for the idea anyways!
