### ISSUE TITLE
So Yeah, i Really Wonder If We Could Equalizing our own Microphone to Sound similar to sounded like the other microphone. like the AutoEQ For Headphone does. So the Question is "Can we AutoEQ our Micrphone to Sounded similar like the neuman flagship or any other Microphone that can Produce a High Quality Voice when We talking?". I really appreciate Everyone if They could Explained Me Deeper about the audio world, since I was newbie onto this community.

### ISSUE THREAD

**Issue by Normalmeep** [jaakkopasanen/AutoEq#509]
**Headphone requests**
Headphone requests are not welcome. If the headphones have not been measured by one of the supported sources, AutoEq cannot support it. If you happen to find a frequency response graph for the headphones, you can create eq settings yourself by following [this guide](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9). Open a headphone request issue only if the headphones have been measured by one of the supported sources but have not been added to AutoEq.

**Comment by dlight** [comment]
Coincidentally I'm also looking for an equalizer for pipewire input (microphones) rather than output (headphones). I was searching AutoEq docs and it looks like it doesn't support this feature :(

My hope was that, since my headphone was measured precisely and it also contains a microphone, AutoEq somehow had measurements for the microphone too buried somewhere. But perhaps calibrating a microphone is an entirely different task (I don't know)

**Comment by jaakkopasanen** [comment]
#510
