### ISSUE TITLE
Add ZSN from Rtings and other target curves

### ISSUE THREAD

**Issue by brbi2kCro** [jaakkopasanen/AutoEq#51]
Hi!

Can you please add KZ ZSN measurement from Rtings.com? It was added about a week ago, and I don't have a working PC to use your app. Also, can you add other target curves as well on measurements (Rtings, Innerfidelity, RAA etc.) like usound and Harman IE17. 

Thanks in advance!

**Comment by jaakkopasanen** [comment]
KZ ZSN is no included.

While there are additional target responses for some databases like Innerfidelity and Rtings it doesn't make sense to provide pre-computed results for those. Usound is given as an alternative to Harman in-ear 2017 target because that is actually based on academic research made on top of Harman in-ear targets. Alternative targets for other databases can still be used when creating custom results but they won't be included into pre-computed results because I want to avoid excess files and bytes for the project. AutoEQ is already a huge for cloning and adding results for multiple new targets would just explode the project size.

**Comment by brbi2kCro** [comment]
Now or not included?

**Comment by jaakkopasanen** [comment]
Ah, sorry. I meant to write: "KZ ZSN is now included" but when I went looking for it, it was missing. It was the only one missing from the new Rtings measurements. But now it is there for sure.

https://github.com/jaakkopasanen/AutoEq/tree/master/results/rtings/avg/KZ%20ZSN
