### ISSUE TITLE
Sloved: About the calibration argument alternative

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [jaakkopasanen/AutoEq#52]
The running command:
```
python .\frequency_response.py --input_dir="C:\AutoEq-master\innerfidelity\data\onear\Audio Technica ATH-M50x" --output_dir="myresults\m50x_simulate_razer_kraken" --compensation="C:\AutoEq-master\rtings\data\onear\Razer Kraken Pro V2\Razer Kraken Pro V2.csv" --calibration="calibration\innerfidelity_to_rtings.csv" --equalize --max_gain 24.0 --treble_max_gain 24.0
```

The console output:
```
frequency_response.py: error: unrecognized arguments: --calibration=calibration\innerfidelity_to_rtings.csv
usage: frequency_response.py [-h] --input_dir INPUT_DIR
                             [--output_dir OUTPUT_DIR] [--standardize_input]
                             [--new_only] [--compensation COMPENSATION]
                             [--equalize] [--parametric_eq] [--fixed_band_eq]
                             [--fc FC] [--q Q] [--ten_band_eq]
                             [--max_filters MAX_FILTERS] [--fs FS]
                             [--bit_depth BIT_DEPTH] [--phase PHASE]
                             [--f_res F_RES] [--bass_boost BASS_BOOST]
                             [--iem_bass_boost IEM_BASS_BOOST] [--tilt TILT]
                             [--sound_signature SOUND_SIGNATURE]
                             [--max_gain MAX_GAIN]
                             [--treble_f_lower TREBLE_F_LOWER]
                             [--treble_f_upper TREBLE_F_UPPER]
                             [--treble_max_gain TREBLE_MAX_GAIN]
                             [--treble_gain_k TREBLE_GAIN_K] [--show_plot]
```

**Comment by jaakkopasanen** [comment]
I removed the calibration argument because it was not really very usable and was altogether confusing. The functionality is now replaced with `--sound_signature` parameter. See here for usage examples: https://github.com/jaakkopasanen/AutoEq#Using-Sound-Signatures

**Comment by mhtvsSFrpHdE** [comment]
I actually working on a script file that able to run AutoEq fast and easy.  
https://github.com/mhtvsSFrpHdE/autoeq-batch-generator/blob/master/autoeq-batch-generator.ps1  
At line 172~178, the "Write" function will generate AutoEq command for later use.  
I read the introduction about the introduction about "Using-Sound-Signatures".  

There are still some specified issue that I'm not sure.  
We know that now I'm going to update my script to match the latest change in AutoEq.  
In the "The running command", for example,  
I use ATH-M50X as my hardware,
and try to equalize this headphone to Razer Kraken(Just for demo & fun).  

I set ```inputDir```, and set compensation file,
in such case the compensation is not from ```innerfidelity``` but the ```inputDir``` is.  
So a calibration file is being used for ```innerfidelity``` to ```rtings```.  

This is the logic behind the old version.  
By reading the introduction I'm not sure how to do same thing in the new version.  
Do you have some suggestion?

**Comment by jaakkopasanen** [comment]
Something like this:
```
python frequency_response.py --input_dir="innerfidelity/data/onear/Audio Technica ATH-M50x" --output_dir="my_results\m50x Kraken" --compensation="innerfidelity\resources\innerfidelity_compensation_sbaf-serious.csv" --sound_signature="results\rtings\avg\Razer Kraken USB\Razer Kraken USB.csv" --equalize --parametric_eq --max_filters=5+5 --ten_band_eq --bass_boost=4
```

Parameters here are:
* `--input_dir` points to the headphones you are using
* `--output_dir` to whatever path you want to save your results in
* `--compensation` must be the path to compensation file for measurement systems used for measuring the headphones you are using which is Innerfidelity in this case
* `--sound_signature` points to a pre-existing equalization result of the target headphone which is Kraken in this case
* `--bass_boost=4` is here because the pre-existing result for Kraken has been made with bass boost of 4dB. Not using bass boost here would result in having less bass than what Kraken has naturally.
* The rest are the usual stuff

`--sound_signature` will use the error curve of the pre-existing result. Sound signature of a headphone is really the deviation from neutral. We assume that the compensation curve represents neutral so deviation (or error) from the compensation curve is the sound signature. This means that the pre-existing result for the target headphone must be made with a neutral compensation curve. Compensation curves used in pre-computed results of AutoEQ are neutral ones (with the exception of bass boost) so the pre-computed results can always be used.

**Comment by mhtvsSFrpHdE** [comment]
@jaakkopasanen So this time we do not compare the difference between the two raw data, instead, but the Razer Kraken "result" is being used.
By my understanding, the new approach that we equalize "M50X" to "sbaf-serious" first, then use "Kraken's result" for sound signature.

Another potential problem is, did the  "sbaf-serious" is the same as "avg"?
Do we need to further calibrate the two?

**Comment by mhtvsSFrpHdE** [comment]
@jaakkopasanen Can you drag a release tag for which commit that removed "--calibration" argument?
So I can drag a release for the API change too.
In this case, is easy to find which version of "AutoEq" can work with "AutoEq batch generator".

There indeed a release in my project, that shows it can work with AutoEq that published around 12/30/2018, but the detailed version is unsure.

https://github.com/mhtvsSFrpHdE/autoeq-batch-generator/releases

**Comment by jaakkopasanen** [comment]
Yes, M50x is first equalized to SBAF-Serious and then to Kraken's sound signature (which is the error curve). Raw data's are not compared directly anymore. SBAF-Serious is not the same as Rting's avg but the whole thing works on the assumption that both of the compensation curves represent neutral for their respective measurement systems. There is no need to calibrate the two systems because having a neutral target for each system works as the calibration mechanism, in a way.

Calibration was removed in this commit: https://github.com/jaakkopasanen/AutoEq/commit/e79b06b6b1375922acb12de7ee85e121ebafe9ba

**Comment by mhtvsSFrpHdE** [comment]
@jaakkopasanen Thank you, I then keep coding.
