### ISSUE TITLE
Equivalent to old --max_filters=n+m

### ISSUE THREAD

**Issue by pureair** [jaakkopasanen/AutoEq#549]
**Is your feature request related to a problem? Please describe.**
--max_filters has been removed from command line options. With --max_filters=n+m, the equalization undergoes two-pass optimization, which sometimes produces better-looking curves. Please consider adding this two-pass feature (main and extra filters) to the parametric-eq configuration profile.
 
**Describe the solution you'd like**
Adding this two-pass feature (main and extra filters) to the parametric-eq configuration profile. For example:

> filters:
>   - type: PEAKING
>   - type: PEAKING
>   - type: PEAKING
>   - type: PEAKING
>   - type: PEAKING, secondary
>   - type: PEAKING, secondary
>   - type: PEAKING, secondary
>   - type: PEAKING, secondary

**Describe alternatives you've considered**

**Additional context**

**Comment by jaakkopasanen** [comment]
You can already achieve this by providing multiple parametric eq configs.

**Comment by pureair** [comment]
> You can already achieve this by providing multiple parametric eq configs.

My bad. I tried "--parametric-eq-config 4_PEAKING_WITH_LOW_SHELF,peq.yaml" and it did't add up. It seems names or YAMLs can stack up, but they can't be mixed together.

**Comment by jaakkopasanen** [comment]
The use case is valid though so I'll look into if I can make them stack up

**Comment by jaakkopasanen** [comment]
I just remembered why I didn't implement this originally. It's because you totally could have a file named `4_PEAKING_WITH_LOW_SHELF,peq.yaml` and at that point it would be impossible to know if you mean this file or if you wish to stack named config with a file. Perhaps there would be a workaround but I think this is too much of a niche feature that I can realistically say I will be putting time to implementing it.
