### ISSUE TITLE
AKG K872 PRO [neutral target] minimum phase filter instead of harman target

### ISSUE THREAD

**Issue by ArkadeFunk** [jaakkopasanen/AutoEq#571]
Since the K872's are reference studio headphones I want to see if there could be a neutral target minimum phase filter made for them instead of the Harman Target. The really want to be able to use these with a neutral frequency response but can't find a preset anywhere so if one could be made that would be amazing. I wasn't sure what category to put this in since there is already a eq filter for the harman target.

**Comment by jaakkopasanen** [comment]
What do you mean by "neutral"? If you mean flat frequency response, then you're misunderstood headphone frequency response measurements because the frequency response isn't supposed to be flat. The measurements are done on measurements systems which simulate human ear and human ear amplifies certain frequencies (most prominently 3 kHz region) and therefore a neutral sounding headphone will have non-flat frequency response. So what is the frequency response of a neutral sounding headphone? It's Harman target.
