### ISSUE TITLE
Crinacles IEC 60318-4 coupler

### ISSUE THREAD

**Issue by markanini** [jaakkopasanen/AutoEq#593]
> Crinacle's in-ear measurements have been performed with IEC 60318-4 coupler and are therefore compatible with Harman in-ear targets. This fact also earns Crinacle's measurements second highest ranking recommendation after oratory1990. Crinacle's over-ear measurements use the same ear simulator attached to a MiniDSP ears pinna. The measurements done on this system are not as accurate as oratory1990's but because of the high quality ear simulator, these are a bit better than rest.

The compatibility of generic couplers with the GRAS RA-series couplers is disputed. Maybe as a minimum this should be mentioned in the readme. And to be prudent, briefly on the ranking page, as some navigate directly to it when being sent a link. Nothing elaborate, just enough that inquiring minds can be made aware.

**Comment by kwisatzsawyer** [comment]
I don't think Crinacle is still using the MiniDSP Ears pinna anymore, but was using a GRAS clone pinna. But regardless, his measurements are unreliable at 8 kHz due to coupler resonance: https://crinacle.com/2020/04/08/graphs-101-how-to-read-headphone-measurements/#elementor-toc__heading-anchor-6

And IEC 60318-4 aren't accurate above 10 kHz. Is there a way for AutoEQ to ignore Crinacle's measurements at 8 khz and all measurements above 10 kHz. Once the public gets access to measurements from B&K Type 5128 (head and torso) or B&K Type 4620 (just the ear and ear cannal simulators) on headphones / IEMs, then we can confidently use AutoEQ's upper treble EQ recommendations.

**Comment by markanini** [comment]
> I don't think Crinacle is still using the MiniDSP Ears pinna anymore, but was using a GRAS clone pinna.

According to his website not using the GRAS for IEm measurement "going forward, the IEM database will continue to use my existing 711 coupler. Certainly not ideal given that it’s still slightly off from a GRAS RA0402"
https://crinacle.com/2020/09/03/in-ear-fidelity-acquires-gras-setup-for-headphone-measurements/

**Comment by jaakkopasanen** [comment]
The deviation with Crinacle's 711 coupler compared to oratory1990's measurements is very low. Keep in mind that these deviations include the unit variance too.

![](https://i.imgur.com/ZDQ00eh.png)

For me this is enough not to put any disclaimers. Certainly this cannot be taken as a blanket statement about all 711 clones but the one Crinacle uses seems to be solid.

**Comment by markanini** [comment]
Since you provide an excellent analysis of the differences between the couplers a simple note on ranking.md would ensure that it won't be missed.
