### ISSUE TITLE
Shelves when filters >10

### ISSUE THREAD

**Issue by deadpenpan** [jaakkopasanen/AutoEq#608]
Hi, 
I made a few modifications to the peq.yaml and constants.py files to be able to generate Parametric EQs with 24 (FabFilter Pro-Q 3) and 99 (MathAudio Headphone EQ) filters. The additions were just to be able to generate and optimize the PEQs but now I'm wondering if, since the choice for the 10kHz shelf was based on the limited number of filters, it would work better if I moved the high shelf up somewhere around 16kHz and let the 97 non-shelf filters do their job between the 20-16k range.

I'm assuming that the 10kHz choice is there to ensure that the 8 peaking filters in a 10-filter PEQ are put to the best use while taking into account the psychoacoustics of the higher range and I am wondering if the extra resolving power that an additional 14 or even 89 peaking filters would provide might ensure more accurate curve-fits that require less granular approximation methods.

Pictured is the 99-filter Harman target correction for my Sony WH-1000XM5 (convolution impulses calculated at 768kHz, 32-bit) in the MathAudio Headphone EQ plug-in for foobar
![image](https://user-images.githubusercontent.com/69339037/221117398-9341bb51-78c0-4c1f-a7f9-bb4fe8035056.png)

**Comment by jaakkopasanen** [comment]
The 10 kHz shelf is at that frequency because only the overall level above 10 kHz matters and therefore it's easy to adjust manually with a 10 kHz high shelf. The measurements aren't accurate above 10 kHz because individual anatomy causes up to 20 dB differences in the response so the range has to be always adjusted manually.

The optimizer won't work well with 99 filters and you'll probably get worse results than with 10. Even 24 is very questionable. The measurements and the target curves aren't so accurate that you would have to care a out very miniscule changes.
