### ISSUE TITLE
oratory1990 Graphic EQ Calculation

### ISSUE THREAD

**Issue by rpx91** [jaakkopasanen/AutoEq#61]
Hi,

I've been trying to use oratory's usound target on my WI-1000x via the graphic EQ text file so that I can use HeSuVi to apply it. But the curve looks really off compared to the actual Parametric EQ on oratory1990's site (https://www.dropbox.com/s/6ml8omtk19t58pf/Sony%20WI-1000X%20%28oratory1990%29.pdf?dl=0) or even the Parametric EQ result in AutoEQ. Seems like a massive bass dip on the Graphic EQ vs Parametric

Is this a bug?

**Comment by jaakkopasanen** [comment]
I tried my best comparing them and to my eyes they look roughly the same. oratory1990 uses about 9 dB bass boost while AutoEQ pre-computed results only have 6 dB for in-ears. This causes the big difference in bass region but other than that both curves look about same.

Here are some things that contribute to differences.  oratory1990 has parametric eq and here you are asking about GraphicEQ which is convolution based equalizer and can do arbitrary shaped curves. AutoEQ's GraphicEQ settings are not the highest resolution so that also plays a role. Axis scales on graphs can play tricks on the eyes so it's important to look at numbers not the curve shapes.

**Comment by rpx91** [comment]
Ah yes - it was in the bass region the curve looked really low.

I'll read the documentation to see how to apply a boost to my liking. I can obviously just use the Parametric EQ from o1990's doc in Peace but HeSuVi's GraphicEQ txt files makes it so easy to keep changing headphones!
