### ISSUE TITLE
Producing 20 band parametric equalizer results

### ISSUE THREAD

**Issue by miimar** [jaakkopasanen/AutoEq#636]
Hi,

I've been learning to use AutoEq and i've gotten great results so far.
Now i hit a brickwall. Is it possible to produce 20 band settings for parametric equalization?
Could you please help me achieve this if so?
I use AutoEq on Windows through Command prompt.

Thank you!

**Comment by jaakkopasanen** [comment]
https://autoeq.app/

Select your headphones, select "Custom Parametric Eq" in the app select and click "ADD FILTER" as many times as needed. Keep in mind that 20 filters might not produce any better results since the optimizer time is limited. Also there really isn't ever a reason to use 20 filters as headphones that cannot be fixed with 10 cannot usually be fixed reliably with 20.
