### ISSUE TITLE
Plans for including other targets?

### ISSUE THREAD

**Issue by eduardoeae** [jaakkopasanen/AutoEq#644]
I was thinking about the IEF 2020 and IEF 2023 targets.

BTW: The new site is amazing. Congrats!

**Comment by jaakkopasanen** [comment]
Thanks!

I'm not sure if I'll include more, at least unless there is a solid research behind the new targets. Right now preferences are fairly easy to adjust with the bass and treble levels, tilt and sound signature. So instead of providing large number of random flavors, my principle is to make it easy for users to create their own flavors.

**Comment by markanini** [comment]
Just some food for thought. Harmans, Oraotry1990s and Moondrops targets are +-1dB from each other between between 300-3000kHz. Given this, a single proven target, as a base, with some personalization options for bass and treble, which AutoEQ currently provides, probably makes the most sense.
![1680892813181](https://github.com/jaakkopasanen/AutoEq/assets/15148553/f751ec12-701e-4e10-b699-f55cccdc87b2)

**Comment by jaakkopasanen** [comment]
Thanks @markanini for the graphs, they really put this into a perspective. With so small differences, ability to change things with already existing controls in the app and the ability to import these files as CSV to the app I'm going to conclude that I won be adding reviewer reference curves.
