### ISSUE TITLE
Option to limit the Hz range of the equalization

### ISSUE THREAD

**Issue by eduardoeae** [jaakkopasanen/AutoEq#654]
I can hear up to 13 kHz and, for me, many equalizations end up with dips or peaks between 8 and 13 kHz.
I would like an option to limit the algorithm to optimize up to a certain range.
PS: This is somehing that [crinacle's](https://crinacle.com/graphs/iems/graphtool) tool has. But I would very much like to have it on AutoEq.

**Comment by jaakkopasanen** [comment]
Do you mean that you'd like there be no changes done beyond certain frequency or that you'd like to have equalization be precise (no smoothing) up to that frequency?

If the former, then you can set treble min and max frequencies where you like and set treble gain multiplier to 0.

If the latter, then you can also set treble min and max frequencies but instead of adjusting treble gain multiplier, adjust treble smoothing window size. But keep in mind that this won't give you more accurate results because the frequency response measurements won't reflect accurately what the frequency response will be with your ears.

**Comment by eduardoeae** [comment]
> Do you mean that you'd like there be no changes done beyond certain frequency or that you'd like to have equalization be precise (no smoothing) up to that frequency?
> 
> If the former, then you can set treble min and max frequencies where you like and set treble gain multiplier to 0.

I like the treble smoothing how it is. Every time I mess with the treble range it ends up with noticeable peaks where there were none before. I think you used to explain this in the main README.md.

> If the latter, then you can also set treble min and max frequencies but instead of adjusting treble gain multiplier, adjust treble smoothing window size. But keep in mind that this won't give you more accurate results because the frequency response measurements won't reflect accurately what the frequency response will be with your ears.

Maybe I am doing something wrong, but treble smoothing only seems to affect the graph, particularly the smoothed raw data. It has no effect on equalizing. Tried it in the webapp and the `--treble-window-size` argument of the app itself.

After taking a look at the code I think I kinda found a way for it to work like I want.
This is how it usually works:
![KZ ZSN Pro_20000](https://github.com/jaakkopasanen/AutoEq/assets/2060444/4a6ea21b-ba90-4f30-94b7-b9f8b9de62fa)

And this with `DEFAULT_F_MAX = 13000.0`
![KZ ZSN Pro_13000](https://github.com/jaakkopasanen/AutoEq/assets/2060444/446a5c3b-6f93-4574-9d73-f904657ba355)

It may not seem as much. But I got better clarity and no new treble peaks.

**Comment by jaakkopasanen** [comment]
I still don't quite understand what you're after here but if you're happy I'm happy.
