### ISSUE TITLE
Add Sony Headphones App EQ to App List

### ISSUE THREAD

**Issue by jet082** [jaakkopasanen/AutoEq#696]
**Is your feature request related to a problem? Please describe.**
As someone just getting into EQ, I find it difficult to translate the existing data into the following EQ app:

<img width="376" alt="image" src="https://github.com/jaakkopasanen/AutoEq/assets/46708077/33006352-cf7d-46c3-9f9f-732a0fb77aeb">

The nice thing about the Sony Headphones EQ app is that the resulting EQ is saved on the headphones and done locally, so you can keep EQ presets across devices.

**Describe the solution you'd like**
Addition of the Sony Headphones EQ parameters to the app list.

**Describe alternatives you've considered**
I tried using "Custom Parametric EQ" to put in the relevant values but I found it very confusing and was unsure what to use in almost every setting.

**Additional context**
No other additional data is needed.

**Comment by jaakkopasanen** [comment]
This covers too few headphones to justify it's place in the list of eq apps.

**Comment by martinhoyer** [comment]
@jaakkopasanen Hi Jaakko! I wonder if this changed, as the Sony WH linup grew since 2023, as did the list of equalizers listed. Sony invested quite a lot into the app, which is now called "Sound Connect". The EQ options didn't change from the screenshot above. 
I can sort-of extrapolate stuff from the existing graphic eq values, but having it in the list either as a "Sony Sound Connect" or generic n-band graphic eq would be lovely. 
That said, I have no idea how the "Clear Bass" fits here :)

**Comment by amethys7dev** [comment]
+1 for Sony SoundConnect
Sure it covers not a lot of models of headphones, but if we're going off units sold instead of different SKUs, that number changes a lot.

I mean.. is this many response curves justified either for the same set of headphones?
<img width="510" height="548" alt="Image" src="https://github.com/user-attachments/assets/491deb95-eb70-4176-a416-8bdb0ed3a46c" />

**Comment by KraXen72** [comment]
Hello, @jaakkopasanen I'd also be interested in this!
If the dropdown for EQ app gets too long, simply add an inline search bar.
Thanks!

**Comment by martinhoyer** [comment]
btw: https://github.com/jaakkopasanen/AutoEq/pull/964
