### ISSUE TITLE
Headphones -> Flat -> Speakers

### ISSUE THREAD

**Issue by AlexFundorin** [jaakkopasanen/AutoEq#70]
Let's say i have a pair of cans. I also have a compensation EQ settings (from here) to make their sound flat.
Already loaded into APO.
Now I want to simulate the frequency response of some common speakers, like NS10, for example, by adding a second entry to my .txt config.
I want to be able to turn on/off different speaker's EQs inside APO on fly.
Where do I get those frequency responses of the popular speaker systems?

**Comment by Pittvandewitt** [comment]
Speakers sound different on your position relative to them. Because of this there's not really a meaningful measurement of a pair of speakers.
My suggestion is to take a look over here to start your journey
https://www.minidsp.com/applications/auto-eq-with-rew

**Comment by jaakkopasanen** [comment]
Exactly what Pittwandewitt said. Frequency response of a speaker system is heavily dominated by the room response instead of the speakers and that changes drastically with the location of the listener and the speakers.

You can take a look at [Impulcifer](https://github.com/jaakkopasanen/Impulcifer) if you want to simulate speaker systems on headphones. However that won't give you the other characteristics than frequency response of a certain loudspeaker because impulse responses only contain linear part of the system ignoring distortion and transient response.

**Comment by AlexFundorin** [comment]
There are two options in the older Sonarworks Reference versions, for example.
1. Calibrate. You can make your headphones response flat. https://i.imgur.com/otVQHGh.png
2. Simulate. On top of a flattened headphones response you can simulate some other cans or a pair of speakers, like NS10. https://i.imgur.com/YaWNFhP.png
I'll take a look at that Impulcifier. Thanks.
