### ISSUE TITLE
Ranking Table

### ISSUE THREAD

**Issue by mttu** [jaakkopasanen/AutoEq#71]
Hi, thanks for your brilliant AutoEQ program, incredible work. I was wondering if it would be possible for you to use your data to produce a ranking table of all the headphones in your full results Index directory? With an option to sort the headphones by average error from their target curve, both before and after equalization? (Possibly also with an option to weight the error across the frequency range according to the equal loudness contour, in order to better represent the subjective perceived difference to the target response.)

I think this would be incredibly valuable for prospective headphone buyers, and would give your AutoEQ tool a big boost in popularity and exposure to the headphone community.

**Comment by jaakkopasanen** [comment]
This was my response in Head-fi. I'll keep this issue open for now in case I decide to implement this for oratory1990 and Crinacle measurements.

It would be possible but doesn't necessarily make as much sense as one might hope. I actually had this at one point but removed it because thought it wasn't very useful. If I would implement it again I would use the preference scoring system by Sean Olive instead of simple average error because it represents our perception a lot better.

There is one big problem however and that's the incompatibility of measurement systems. The ranking would only really make sense for oratory1990's and crinacle's measurments. Other measurement systems are not compatible with Olive's research and do not represent human hearing accurately enough. One could argue that the same applies for equalization but the equalization settings produced from measurements made with other systems are the best guesses into right direction, sort of attempts to be at least better than nothing. It wouldn't be apples to apples comparison to rank measurements from multiple different measurement systems even if the equalization settings work independently.

I might implement this at some point for oratory1990's and Crinacle's measurements. Different sorting options is not going to be possible unfortunately because it's very limited what one can do with Github Markdown documents. Basically it would be a table sorted by the Harman preference score before equalization.

**Comment by mttu** [comment]
Thanks for the response. I think even a ranking table just using oratory1990 and Crinacle's measurements would be a really useful addition, as they've measured a good sample of headphones between them. I hope you get the time to add this to the project, and thanks again for all the hard work in creating AutoEQ!

**Comment by jaakkopasanen** [comment]
Here it is: https://github.com/jaakkopasanen/AutoEq/blob/master/results/RANKING.md

Includes headphones measured by oratory1990 and IEMs measured by oratory1990 and Crinacle
