### ISSUE TITLE
Measurement changed on the website

### ISSUE THREAD

**Issue by Strange96** [jaakkopasanen/AutoEq#729]
Hello,
First of all, thanks for creating such a great project! It's been my go to for dialing in my headphone eqs for a while.
I've noticed that the profile for the Kiwi Ears Orchestra that I currently use has changed recently. Previously, this was using Crinacle 711 but now I only see Bruel & Kjaer. I see both are in the list of the Crinacle results:

![image](https://github.com/jaakkopasanen/AutoEq/assets/25486876/d761b0f1-8f57-47a0-bdb8-d3a8e4adfd67)

Is there some way I can import/access the 711 on the website?

**Comment by jaakkopasanen** [comment]
You can now choose to see all measurements, not just the recommended ones. At the bottom of the headphone selector.

The 711 measurements disappeared because there was a bug with how the recommendations were created and that caused the 711 measurement to be recommended over BK 4620 measurement. I fixed the bug so then you could only see the 4620 measurement. Now you have a choice.

**Comment by mstrange96** [comment]
Great, thank you!
