### ISSUE TITLE
Hesuvi usage guide for the new measurements?

### ISSUE THREAD

**Issue by codeitout32** [jaakkopasanen/AutoEq#742]
I'm a big user for Hesuvi. I want to use the measurments. I Dont know what target they are focusing and what will be the correct way to use it with hesuvi.
I like hesuvi because of the quick working it provides.

For meantime i copy the graphic eq csv and paste it in a custom hesuvi profile does it require anything else please let us know.

**Comment by jaakkopasanen** [comment]
I'm not sure what you're asking for. Could you elaborate?

**Comment by jaakkopasanen** [comment]
https://sourceforge.net/p/hesuvi/wiki/Help/#updating-equalizer-profiles if you want to have the latest AutoEq profiles.

And of course you can simply take a single GraphicEq.txt files and drop it to Custom folder. You then of course need to select the file in HeSuVi. HeSuVi UI only shows 12 dB of positive or negative gain for Custom eq profiles but if you download one from AutoEq, the file might contain larger (absolute) values. In this case only the UI will be wrong.

**Comment by codeitout32** [comment]
okay, thanks that would be enough for me. 
I have some doubts 
i) are the graphic eq profiles are inferior to parametric ones.
ii) are these new profiles are targeting any new target instead of harmon? bcoz these are very different compared to 2020 ones. those are very soothing.

**Comment by jaakkopasanen** [comment]
Many things have changed since 2020. It's impossible to say what might be the difference that causes what you perceive. Targets too might have changed but probably not to be brighter. You can always cook up your own in autoeq.app. If you wish to have darker sound, set the tilt knob to negative values. Or drag down the treble boost gain (and potentially treble boost frequency too).

GraphicEq profiles are not inferior to parametric eq. A bit more accurate in fact, althought in most cases that won't matter as the headphone unit variance and the natural variance between listeners is greater typically.
