### ISSUE TITLE
Will 0dB Review measurements database be implemented in Autoeq?

### ISSUE THREAD

**Issue by Prolatus** [jaakkopasanen/AutoEq#771]
Will 0dB Review measurements database be implemented in Autoeq?

He has the same rig as Crinacle does and some nice measurements and reviews.

**Comment by jaakkopasanen** [comment]
There's already quite a few databases supported. At one point I promised to myself that I wouldn't add any more (had maybe 5 at the time) and then I added like 20 more. But this was because all of them used cringraphers so I didn't have to build separate custom crawlers for all of them. These ones don't seem to do that and therefore it's not worth it for me to put the time into supporting these.
